import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';

const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const enc=new TextEncoder();
function parseSig(v:string){const out:any={};for(const part of String(v||'').split(',')){const [k,...rest]=part.trim().split('=');if(k&&rest.length)out[k]=rest.join('=');}return out;}
function hex(bytes:ArrayBuffer){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function equalHex(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0;}
async function validSignature(secret:string,dataId:string,requestId:string,signature:string){const p=parseSig(signature),ts=String(p.ts||''),v1=String(p.v1||'');if(!ts||!v1)return false;const bits:string[]=[];if(dataId)bits.push(`id:${dataId}`);if(requestId)bits.push(`request-id:${requestId}`);bits.push(`ts:${ts}`);const manifest=bits.join(';')+';';const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const digest=hex(await crypto.subtle.sign('HMAC',key,enc.encode(manifest)));return equalHex(digest.toLowerCase(),v1.toLowerCase());}
async function backendSecret(sb:any,name:string){const envValue=Deno.env.get(name);if(envValue)return envValue;const {data,error}=await sb.rpc('ld_backend_secret',{p_name:name});if(error)return '';return String(data||'');}
function publicPayment(p:any){const tx=p?.point_of_interaction?.transaction_data||{};return {id:p?.id?String(p.id):null,status:p?.status||null,status_detail:p?.status_detail||null,payment_method_id:p?.payment_method_id||null,payment_type_id:p?.payment_type_id||null,date_of_expiration:p?.date_of_expiration||null,qr_code:tx.qr_code||null,qr_code_base64:tx.qr_code_base64||null,ticket_url:tx.ticket_url||null};}
function subStatus(v:string){const s=String(v||'').toLowerCase();if(s==='authorized')return 'authorized';if(s==='paused')return 'paused';if(s==='cancelled'||s==='canceled')return 'cancelled';if(s==='pending')return 'pending';return 'failed';}
function addPeriod(plan:any,from:Date){const d=new Date(from);if(plan.billing_frequency_type==='years')d.setUTCFullYear(d.getUTCFullYear()+Number(plan.billing_frequency||1));else d.setUTCMonth(d.getUTCMonth()+Number(plan.billing_frequency||1));return d;}
function validDate(value:any){const d=value?new Date(value):null;return d&&Number.isFinite(d.getTime())?d:null;}
async function syncPreapproval(sb:any,access:string,providerId:string){const r=await fetch(`https://api.mercadopago.com/preapproval/${encodeURIComponent(providerId)}`,{headers:{Authorization:`Bearer ${access}`}});const mp=await r.json().catch(()=>({}));if(!r.ok)throw new Error('SUBSCRIPTION_FETCH_FAILED');let q=sb.from('ld_subscriptions').select('*');q=mp.external_reference?q.eq('id',String(mp.external_reference)):q.eq('provider_subscription_id',String(mp.id));const {data:sub,error}=await q.maybeSingle();if(error||!sub)throw new Error('SUBSCRIPTION_NOT_FOUND');const status=subStatus(mp.status);const next=validDate(mp.next_payment_date);await sb.from('ld_subscriptions').update({provider_subscription_id:String(mp.id),status,next_payment_at:next?.toISOString()||sub.next_payment_at||null,canceled_at:status==='cancelled'?(sub.canceled_at||new Date().toISOString()):sub.canceled_at,updated_at:new Date().toISOString(),metadata:{...(sub.metadata||{}),provider_status:mp.status||null,payment_authoritative_entitlement:true}}).eq('id',sub.id);return {subscription_id:sub.id,status,current_period_end:sub.current_period_end||null,access_changed:false,payment_authoritative_entitlement:true};}
async function processAuthorizedPayment(sb:any,access:string,invoiceId:string){const r=await fetch(`https://api.mercadopago.com/authorized_payments/${encodeURIComponent(invoiceId)}`,{headers:{Authorization:`Bearer ${access}`}});const inv=await r.json().catch(()=>({}));if(!r.ok)throw new Error('AUTHORIZED_PAYMENT_FETCH_FAILED');const preapprovalId=String(inv.preapproval_id||'');if(!preapprovalId)throw new Error('SUBSCRIPTION_ID_MISSING');const {data:sub,error}=await sb.from('ld_subscriptions').select('*,plan:ld_commercial_plans(*)').eq('provider_subscription_id',preapprovalId).maybeSingle();if(error||!sub)throw new Error('SUBSCRIPTION_NOT_FOUND');const {data:license}=await sb.from('ld_license_keys').select('expires_at').eq('id',sub.license_id).maybeSingle();const paymentStatus=String(inv?.payment?.status||inv?.summarized||inv?.status||'pending');let providerPeriodEnd=validDate(sub.current_period_end)||new Date();let entitlementEnd=validDate(license?.expires_at)||new Date();if(paymentStatus==='approved'){
    const pr=await fetch(`https://api.mercadopago.com/preapproval/${encodeURIComponent(preapprovalId)}`,{headers:{Authorization:`Bearer ${access}`}});const p=await pr.json().catch(()=>({}));const providerNext=validDate(p?.next_payment_date);providerPeriodEnd=providerNext||addPeriod(sub.plan,new Date());const previousExpiry=validDate(license?.expires_at);entitlementEnd=new Date(Math.max(providerPeriodEnd.getTime(),previousExpiry?.getTime()||0,Date.now()));await sb.from('ld_subscriptions').update({status:'authorized',current_period_start:new Date().toISOString(),current_period_end:providerPeriodEnd.toISOString(),next_payment_at:providerNext?.toISOString()||providerPeriodEnd.toISOString(),last_payment_id:String(inv?.payment?.id||invoiceId),last_payment_status:'approved',updated_at:new Date().toISOString(),metadata:{...(sub.metadata||{}),payment_authoritative_entitlement:true,entitlement_before_payment_expires_at:previousExpiry?.toISOString()||null,entitlement_after_payment_expires_at:entitlementEnd.toISOString()}}).eq('id',sub.id);await sb.from('ld_license_keys').update({commercial_tier:'subscription',byok_allowed:Boolean(sub.plan?.byok_allowed),expires_at:entitlementEnd.toISOString(),status:'active',updated_at:new Date().toISOString()}).eq('id',sub.license_id);
  }else{await sb.from('ld_subscriptions').update({last_payment_id:String(inv?.payment?.id||invoiceId),last_payment_status:paymentStatus,updated_at:new Date().toISOString()}).eq('id',sub.id);}return {subscription_id:sub.id,payment_status:paymentStatus,current_period_end:providerPeriodEnd.toISOString(),entitlement_expires_at:entitlementEnd.toISOString(),access_changed:paymentStatus==='approved',payment_authoritative_entitlement:true};}
async function fulfill(sb:any,order:any){if(order.status==='fulfilled')return {ok:true,duplicate:true};let licenseId=order.existing_license_id||order.issued_license_id||null;let newKey:string|null=null;if(!licenseId){const base=Deno.env.get('SUPABASE_URL')||'',owner=await backendSecret(sb,'LD_OWNER_SECRET');if(!owner)throw new Error('OWNER_SECRET_NOT_CONFIGURED');const r=await fetch(`${base}/functions/v1/ld-license-admin`,{method:'POST',headers:{'content-type':'application/json','x-owner-secret':owner},body:JSON.stringify({action:'generate_identity',label:`Compra ${order.id}`,customer_email:order.customer_email,source_order_id:order.id,max_devices:1,vault_api_base:`${base}/functions/v1/ld-vault`,update_feed_url:`${base}/functions/v1/ld-release-feed`})});const x=await r.json().catch(()=>({}));if(!r.ok||!x?.ok||!x?.license?.id||!x?.key)throw new Error(x?.code||'LICENSE_ISSUE_FAILED');licenseId=x.license.id;newKey=x.key;}await sb.from('ld_orders').update({issued_license_id:licenseId,status:'fulfilling',approved_at:order.approved_at||new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',order.id);const {data:applied,error}=await sb.rpc('ld_apply_order_entitlement',{p_order_id:order.id,p_license_id:licenseId});if(error||!applied?.ok)throw new Error(applied?.code||'ENTITLEMENT_FAILED');if(newKey)await sb.from('ld_order_deliveries').upsert({order_id:order.id,license_key:newKey,expires_at:new Date(Date.now()+24*3600000).toISOString()},{onConflict:'order_id'});return {ok:true,license_id:licenseId,new_key:Boolean(newKey)};}

Deno.serve(async req=>{
  if(req.method!=='POST')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);
  let eventRow:string|null=null;
  try{
    const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!service)return json({ok:false,code:'BACKEND_NOT_CONFIGURED'},503);const sb=createClient(url,service,{auth:{persistSession:false}});const secret=await backendSecret(sb,'MERCADOPAGO_WEBHOOK_SECRET'),access=await backendSecret(sb,'MERCADOPAGO_ACCESS_TOKEN');if(!secret||!access)return json({ok:false,code:'MERCADOPAGO_NOT_CONFIGURED'},503);const body=await req.json().catch(()=>({}));const parsedUrl=new URL(req.url);const dataId=String(body?.data?.id||parsedUrl.searchParams.get('data.id')||parsedUrl.searchParams.get('id')||'').toLowerCase();const requestId=String(req.headers.get('x-request-id')||'');const signature=String(req.headers.get('x-signature')||'');const okSig=await validSignature(secret,dataId,requestId,signature);const eventType=String(body?.type||body?.action||'payment');const sigParts=parseSig(signature);const eventKey=[eventType,dataId,requestId,String(sigParts.ts||'')].join(':');const {data:inserted}=await sb.from('ld_webhook_events').upsert({provider:'mercadopago',event_key:eventKey,event_type:eventType,resource_id:dataId||null,signature_valid:okSig,payload:body},{onConflict:'event_key',ignoreDuplicates:true}).select('id,processed').maybeSingle();eventRow=inserted?.id||null;if(!okSig)return json({ok:false,code:'INVALID_SIGNATURE'},401);if(!dataId)return json({ok:true,ignored:true,reason:'NO_RESOURCE_ID'});if(inserted?.processed)return json({ok:true,duplicate:true});
    if(eventType==='subscription_preapproval'){
      const result=await syncPreapproval(sb,access,dataId);await sb.from('ld_subscription_events').upsert({subscription_id:result.subscription_id,provider:'mercadopago',event_key,event_type,resource_id:dataId,outcome:'processed',payload:body,processed_at:new Date().toISOString()},{onConflict:'event_key'});if(eventRow)await sb.from('ld_webhook_events').update({processed:true,processed_at:new Date().toISOString(),error_code:null}).eq('id',eventRow);return json({ok:true,processed:true,result});
    }
    if(eventType==='subscription_authorized_payment'){
      const result=await processAuthorizedPayment(sb,access,dataId);await sb.from('ld_subscription_events').upsert({subscription_id:result.subscription_id,provider:'mercadopago',event_key,event_type,resource_id:dataId,outcome:'processed',payload:body,processed_at:new Date().toISOString()},{onConflict:'event_key'});if(eventRow)await sb.from('ld_webhook_events').update({processed:true,processed_at:new Date().toISOString(),error_code:null}).eq('id',eventRow);return json({ok:true,processed:true,result});
    }
    if(eventType==='subscription_preapproval_plan'){if(eventRow)await sb.from('ld_webhook_events').update({processed:true,processed_at:new Date().toISOString(),error_code:null}).eq('id',eventRow);return json({ok:true,ignored:true,reason:'PLAN_EVENT'});}
    const mpRes=await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(dataId)}`,{headers:{Authorization:`Bearer ${access}`}});const mp=await mpRes.json().catch(()=>({}));if(!mpRes.ok){if(eventRow)await sb.from('ld_webhook_events').update({error_code:'PAYMENT_FETCH_FAILED',processed_at:new Date().toISOString()}).eq('id',eventRow);return json({ok:false,code:'PAYMENT_FETCH_FAILED'},502);}const orderId=String(mp.external_reference||mp?.metadata?.ld_order_id||'');let q=sb.from('ld_orders').select('*');q=/^[0-9a-f-]{36}$/i.test(orderId)?q.eq('id',orderId):q.eq('mercadopago_payment_id',String(mp.id));const {data:order,error:oe}=await q.maybeSingle();if(oe||!order){if(eventRow)await sb.from('ld_webhook_events').update({error_code:'ORDER_NOT_FOUND',processed_at:new Date().toISOString()}).eq('id',eventRow);return json({ok:false,code:'ORDER_NOT_FOUND'},404);}const actualCents=Math.round(Number(mp.transaction_amount||0)*100);if(actualCents!==Number(order.amount_cents)){if(eventRow)await sb.from('ld_webhook_events').update({error_code:'AMOUNT_MISMATCH',processed_at:new Date().toISOString()}).eq('id',eventRow);return json({ok:false,code:'AMOUNT_MISMATCH'},409);}const pub=publicPayment(mp);await sb.from('ld_payments').update({provider_payment_id:String(mp.id),status:String(mp.status||'pending'),status_detail:mp.status_detail||null,payment_method_id:mp.payment_method_id||null,provider_public_data:pub,updated_at:new Date().toISOString()}).eq('order_id',order.id);await sb.from('ld_orders').update({mercadopago_payment_id:String(mp.id),payment_method:mp.payment_method_id||order.payment_method,updated_at:new Date().toISOString()}).eq('id',order.id);let result:any={status:mp.status};if(mp.status==='approved'){await sb.from('ld_orders').update({status:'fulfilling',approved_at:order.approved_at||new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',order.id);result=await fulfill(sb,{...order,status:'fulfilling',approved_at:order.approved_at||new Date().toISOString()});}else if(mp.status==='refunded'||mp.status==='charged_back'){const reason=mp.status==='charged_back'?'chargeback':'refund';const {data:r,error:re}=await sb.rpc('ld_reverse_order_entitlement',{p_order_id:order.id,p_reason:reason});if(re)throw re;result=r;}else if(mp.status==='cancelled'||mp.status==='rejected'){await sb.from('ld_orders').update({status:mp.status==='cancelled'?'cancelled':'failed',updated_at:new Date().toISOString()}).eq('id',order.id);}else await sb.from('ld_orders').update({status:'payment_pending',updated_at:new Date().toISOString()}).eq('id',order.id);if(eventRow)await sb.from('ld_webhook_events').update({processed:true,processed_at:new Date().toISOString(),error_code:null}).eq('id',eventRow);return json({ok:true,processed:true,result});
  }catch(e){console.error('ld-mercadopago-webhook',e);try{const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(eventRow&&url&&service){const sb=createClient(url,service,{auth:{persistSession:false}});await sb.from('ld_webhook_events').update({error_code:String((e as Error).message||'INTERNAL_ERROR').slice(0,120),processed_at:new Date().toISOString()}).eq('id',eventRow);}}catch{}return json({ok:false,code:'INTERNAL_ERROR'},500);}
});
