import { createClient } from "jsr:@supabase/supabase-js@2";

const PUBLIC_SPKI_B64="MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/suDKmZG7B52xCVkCooS5MZfvVu+GjYTIfeOvlfi9tz29TQNN4uea318Nn2xf5uf/cm0bpaCADPwkqWSZV2MIA==";
const FREE_MODELS=["gemini-3.6-flash","gemini-3.5-flash-lite","gemini-2.5-pro","gemini-2.5-flash","gemini-2.5-flash-lite"];
const LOCAL_PROVIDER="decrypter-local";
const LOCAL_DEFAULT_MODEL="decrypter-local";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-license-key,x-device-id,x-gemini-key,x-decrypter-gateway,x-decrypter-gateway-signature,authorization","Access-Control-Allow-Methods":"POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
const enc=new TextEncoder();

function u(v:string){const s=v.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(v.length/4)*4,"=");return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",enc.encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("");}
async function hmacHex(secret:string,value:string){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=await crypto.subtle.sign("HMAC",key,enc.encode(value));return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,"0")).join("");}
function safeEq(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function internalAllowed(req:Request,serviceRole:string,commandId:string){const got=String(req.headers.get("x-decrypter-gateway-signature")||"").trim();if(!got)return false;const expected=await hmacHex(serviceRole,`ld-gateway:${commandId}`);return safeEq(got,expected);}
async function verifyToken(token:string){const [p,pp,sp]=token.split(".");if(p!=="LD2"||!pp||!sp)throw new Error("KEY_INVALID_FORMAT");const der=Uint8Array.from(atob(PUBLIC_SPKI_B64),c=>c.charCodeAt(0));const pk=await crypto.subtle.importKey("spki",der,{name:"ECDSA",namedCurve:"P-256"},false,["verify"]);if(!await crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},pk,u(sp),enc.encode(pp)))throw new Error("KEY_INVALID_SIGNATURE");const payload=JSON.parse(new TextDecoder().decode(u(pp)));const now=Math.floor(Date.now()/1000);if(payload?.aud!=="lovable-decrypter"||Number(payload?.v)!==1||!payload?.license_id)throw new Error("KEY_INVALID_PAYLOAD");if(payload.nbf&&now<Number(payload.nbf))throw new Error("KEY_NOT_ACTIVE");return payload;}
function modelId(v:string){return String(v||"").trim().replace(/^models\//,"");}
function freeModel(v:string){const id=modelId(v);return FREE_MODELS.includes(id)||FREE_MODELS.some(x=>id===`${x}-latest`||id===`${x}-001`);}
function supportedTextModel(v:string){const id=modelId(v).toLowerCase();return /^gemini-[a-z0-9._-]+$/.test(id)&&!/(embedding|imagen|veo|tts|live|native-audio|image-generation|aqa|robotics)/.test(id);}
function extractGemini(data:any){if(typeof data?.output_text==="string"&&data.output_text)return data.output_text;const chunks:string[]=[];for(const step of Array.isArray(data?.steps)?data.steps:[])if(step?.type==="model_output"&&Array.isArray(step.content))for(const p of step.content)if(p?.type==="text"&&typeof p.text==="string")chunks.push(p.text);return chunks.join("");}
function extractLocal(data:any){const content=data?.choices?.[0]?.message?.content;if(typeof content==="string")return content;if(Array.isArray(content))return content.map((part:any)=>typeof part?.text==="string"?part.text:"").join("");return "";}
function stripJsonFence(value:string){const text=String(value||"").trim();const match=text.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);return match?match[1].trim():text;}
function compact(v:unknown,max=2_500_000){let s="";try{s=typeof v==="string"?v:JSON.stringify(v??{});}catch{s="{}";}return s.length>max?s.slice(0,max)+"\n...[contexto truncado pelo backend]":s;}
function media(items:any[]){const out:any[]=[];let total=0;for(const a of items.slice(0,8)){const mime=String(a?.mime_type||a?.mimeType||a?.type||"application/octet-stream");const data=String(a?.data||"");const name=String(a?.name||"anexo").slice(0,180);if(!data)continue;total+=data.length;if(total>20_000_000)break;out.push({type:"text",text:`ANEXO DE REFERÊNCIA: ${name} (${mime})`});let type="document";if(mime.startsWith("image/"))type="image";else if(mime.startsWith("audio/"))type="audio";else if(mime.startsWith("video/"))type="video";out.push({type,data,mime_type:mime});}return out;}
function localTextCompatible(items:any[]){return items.every(a=>/^(text\/|application\/(json|xml|javascript|typescript|x-javascript))/i.test(String(a?.mime_type||a?.mimeType||"")));}
function decodeTextData(value:string){try{let raw=String(value||"");const comma=raw.indexOf(",");if(/^data:/i.test(raw)&&comma>=0)raw=raw.slice(comma+1);const binary=atob(raw);return new TextDecoder().decode(Uint8Array.from(binary,c=>c.charCodeAt(0)));}catch{return "";}}
function localAttachmentBlock(items:any[]){let total=0;const blocks:string[]=[];for(const a of items.slice(0,8)){const mime=String(a?.mime_type||a?.mimeType||"");if(!/^(text\/|application\/(json|xml|javascript|typescript|x-javascript))/i.test(mime))continue;const decoded=decodeTextData(String(a?.data||""));if(!decoded)continue;const allowed=Math.max(0,1_500_000-total);if(!allowed)break;const body=decoded.slice(0,allowed);total+=body.length;blocks.push(`\n===== ATTACHMENT: ${String(a?.name||"anexo").slice(0,180)} (${mime}) =====\n${body}`);}return blocks.join("\n");}
function deleteIntent(c:string){return /\b(remov(?:a|er)|exclu(?:a|ir)|apag(?:ue|ar)|delet(?:e|ar)|delete|remove)\b/i.test(c);}
const PLAN_SCHEMA={type:"object",properties:{summary:{type:"string"},plan:{type:"array",items:{type:"string"}},files:{type:"array",items:{type:"object",properties:{path:{type:"string"},reason:{type:"string"}},required:["path","reason"]}},warnings:{type:"array",items:{type:"string"}}},required:["summary","plan","files","warnings"]};
const EDIT_SCHEMA={type:"object",properties:{summary:{type:"string"},plan:{type:"array",items:{type:"string"}},files:{type:"array",items:{type:"object",properties:{path:{type:"string"},action:{type:"string",enum:["create","update","delete"]},content:{type:"string"},edits:{type:"array",items:{type:"object",properties:{search:{type:"string"},replace:{type:"string"}},required:["search","replace"]}},explanation:{type:"string"}},required:["path","action","content","edits","explanation"]}},dependencies:{type:"array",items:{type:"string"}},warnings:{type:"array",items:{type:"string"}},commit_message:{type:"string"}},required:["summary","plan","files","dependencies","warnings","commit_message"]};
function validateBuild(result:any,ctx:any,command:string){if(!result||!Array.isArray(result.files))return {ok:false,code:"INVALID_BUILD_SHAPE"};if(result.files.length>30)return {ok:false,code:"TOO_MANY_FILES"};const originals=new Map<string,string>();for(const f of Array.isArray(ctx?.files)?ctx.files:[])if(f?.path&&typeof f?.content==="string")originals.set(String(f.path),f.content);for(const f of result.files){const path=String(f?.path||"");if(!path||path.startsWith("/")||path.includes(".."))return {ok:false,code:"UNSAFE_PATH",path};if(f.action==="update"){if(f.content!=="")return {ok:false,code:"UPDATE_CONTENT_MUST_BE_EMPTY",path};if(!Array.isArray(f.edits)||!f.edits.length)return {ok:false,code:"PATCH_REQUIRED",path};const original=originals.get(path);for(const op of f.edits){const search=String(op?.search||"");if(!search)return {ok:false,code:"EMPTY_SEARCH",path};if(typeof original==="string"){const first=original.indexOf(search),last=original.lastIndexOf(search);if(first<0)return {ok:false,code:"SEARCH_NOT_FOUND",path};if(first!==last)return {ok:false,code:"SEARCH_AMBIGUOUS",path};const lines=Math.max(1,original.split("\n").length),sl=Math.max(1,search.split("\n").length);if(lines>=30&&sl/lines>0.65)return {ok:false,code:"PATCH_TOO_LARGE",path};if(search.length>24000)return {ok:false,code:"PATCH_TOO_LARGE",path};}}}else if(f.action==="create"){if(typeof f.content!=="string"||!f.content)return {ok:false,code:"CREATE_CONTENT_REQUIRED",path};if(Array.isArray(f.edits)&&f.edits.length)return {ok:false,code:"CREATE_EDITS_FORBIDDEN",path};}else if(f.action==="delete"){if(!deleteIntent(command))return {ok:false,code:"DELETE_NOT_EXPLICIT",path};}else return {ok:false,code:"UNKNOWN_FILE_ACTION",path};}return {ok:true};}
function localConfig(){return {url:String(Deno.env.get("DECRYPTER_LOCAL_URL")||"").replace(/\/+$/,"") ,token:String(Deno.env.get("DECRYPTER_LOCAL_TOKEN")||""),servedModel:String(Deno.env.get("DECRYPTER_LOCAL_MODEL")||LOCAL_DEFAULT_MODEL),label:String(Deno.env.get("DECRYPTER_LOCAL_MODEL_LABEL")||"Qwen/Qwen3-Coder-30B-A3B-Instruct")};}
async function localHealth(timeoutMs=2500){const cfg=localConfig();if(!cfg.url||!cfg.token)return {configured:false,healthy:false,code:"LOCAL_RUNTIME_NOT_CONFIGURED",served_model:cfg.servedModel,model_label:cfg.label,latency_ms:null};const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);const started=Date.now();try{const res=await fetch(`${cfg.url}/v1/models`,{headers:{Authorization:`Bearer ${cfg.token}`},signal:controller.signal});const body=await res.json().catch(()=>({}));const ids=(Array.isArray(body?.data)?body.data:[]).map((x:any)=>String(x?.id||""));const loaded=ids.includes(cfg.servedModel);return {configured:true,healthy:res.ok&&loaded,code:res.ok?(loaded?"OK":"LOCAL_MODEL_NOT_LOADED"):`LOCAL_HEALTH_HTTP_${res.status}`,served_model:cfg.servedModel,model_label:cfg.label,models:ids.slice(0,20),latency_ms:Date.now()-started};}catch(e){return {configured:true,healthy:false,code:(e as Error)?.name==="AbortError"?"LOCAL_HEALTH_TIMEOUT":"LOCAL_HEALTH_FAILED",served_model:cfg.servedModel,model_label:cfg.label,latency_ms:Date.now()-started};}finally{clearTimeout(timer);}}
function telemetry(provider:string,raw:any){const usage=raw?.usage||{};const input=usage.input_tokens??usage.prompt_tokens??usage.total_input_tokens??usage.promptTokenCount??null;const output=usage.output_tokens??usage.completion_tokens??usage.total_output_tokens??usage.candidatesTokenCount??null;const total=usage.total_tokens??usage.totalTokenCount??((input!=null&&output!=null)?Number(input)+Number(output):null);return {reported:[input,output,total].some(v=>v!=null),provider,inputTokens:input==null?null:Number(input),outputTokens:output==null?null:Number(output),totalTokens:total==null?null:Number(total),cost:null,currency:null};}

Deno.serve(async req=>{
  if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});
  if(req.method!=="POST")return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);
  const started=Date.now();let logId:string|null=null;let sb:any=null;let licenseId:string|null=null;let commandId:string|null=null;
  try{
    const body=await req.json().catch(()=>({}));
    commandId=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(body.command_id||""))?String(body.command_id):crypto.randomUUID();
    const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    if(!url||!service)return json({ok:false,code:"BACKEND_NOT_CONFIGURED"},503);

    if(String(body.action||"")==="provider_status"){
      if(!await internalAllowed(req,service,commandId))return json({ok:false,code:"INTERNAL_SIGNATURE_REQUIRED"},403);
      return json({ok:true,provider:LOCAL_PROVIDER,runtime:await localHealth(),schema:"ld-local-runtime/1"});
    }

    const bearer=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();
    const token=String(req.headers.get("x-license-key")||body.license_key||bearer||"").trim();
    const deviceId=String(req.headers.get("x-device-id")||body.device_id||"").trim();
    const provider=String(body.provider||"gemini")==="decrypter-local"?LOCAL_PROVIDER:"gemini";
    const geminiKey=String(req.headers.get("x-gemini-key")||body.gemini_api_key||"").trim();
    const mode=body.mode==="plan"?"plan":"build";
    const billingMode=body.gemini_billing_mode==="user_paid"||body.billing_mode==="user_paid"?"user_paid":"free";
    const command=String(body.command||"").trim();
    const ctx=body.project_context||{};
    const approved=body.approved_plan||null;
    const rules=String(body.agent_rules||"").slice(0,200000);
    const attachments=Array.isArray(body.attachments)?body.attachments:[];
    let model=provider===LOCAL_PROVIDER?localConfig().servedModel:modelId(String(body.model||"gemini-3.6-flash"));
    if(!command)return json({ok:false,code:"COMMAND_REQUIRED"},400);
    if(provider===LOCAL_PROVIDER){if(!await internalAllowed(req,service,commandId))return json({ok:false,code:"LOCAL_PROVIDER_GATEWAY_ONLY"},403);if(!localTextCompatible(attachments))return json({ok:false,code:"LOCAL_ATTACHMENTS_NOT_SUPPORTED"},400);const health=await localHealth();if(!health.healthy)return json({ok:false,code:health.code||"LOCAL_RUNTIME_UNAVAILABLE",runtime:health},503);}else{if(!geminiKey)return json({ok:false,code:"GEMINI_KEY_REQUIRED"},400);if(!supportedTextModel(model))return json({ok:false,code:"MODEL_NOT_SUPPORTED",model},400);if(billingMode==="free"&&!freeModel(model))return json({ok:false,code:"ZERO_COST_MODEL_BLOCKED",message:`Modelo ${model} não está na allowlist gratuita verificada. Ative explicitamente o modo pago da sua própria API para usá-lo.`},400);}

    let signed:any;try{signed=await verifyToken(token);}catch(e){return json({ok:false,code:String((e as Error).message||e)},403);}
    sb=createClient(url,service,{auth:{persistSession:false}});
    const {data:license,error:le}=await sb.from("ld_license_keys").select("id,status,max_devices,expires_at,access_mode,credit_balance,credit_debt,command_remainder,commands_per_credit").eq("id",String(signed.license_id)).eq("key_hash",await sha(token)).maybeSingle();
    if(le)return json({ok:false,code:"DB_ERROR"},500);if(!license)return json({ok:false,code:"KEY_NOT_REGISTERED"},403);licenseId=license.id;if(license.status!=="active")return json({ok:false,code:"KEY_"+String(license.status).toUpperCase()},403);if(!deviceId)return json({ok:false,code:"DEVICE_REQUIRED"},403);
    const dh=await sha(deviceId);const {data:dev}=await sb.from("ld_license_devices").select("id,revoked_at").eq("license_id",license.id).eq("device_hash",dh).maybeSingle();if(!dev)return json({ok:false,code:"DEVICE_NOT_BOUND"},403);if(dev.revoked_at)return json({ok:false,code:"DEVICE_REVOKED"},403);await sb.from("ld_license_devices").update({last_seen_at:new Date().toISOString()}).eq("id",dev.id);
    const {data:reservation,error:re}=await sb.rpc("ld_reserve_command",{p_license_id:license.id,p_command_id:commandId,p_mode:mode});if(re){console.error(re);return json({ok:false,code:"CREDIT_RESERVATION_FAILED"},500);}if(!reservation?.allowed)return json({ok:false,code:reservation?.code||"ENTITLEMENT_EXHAUSTED",entitlement:reservation},403);if(reservation?.duplicate)return json({ok:false,code:"DUPLICATE_COMMAND",command_id:commandId,charged_again:false,previous_status:reservation.status||null},409);
    const {data:lr}=await sb.from("ld_command_logs").insert({license_id:license.id,device_hash:dh,mode,model:`${provider}:${model}`,command_chars:command.length,attachment_count:attachments.length,status:"started"}).select("id").single();logId=lr?.id||null;
    const system=mode==="plan"?`Você é o agente de planejamento do Lovable Decrypter v2. Não escreva código. Produza somente um plano objetivo, estritamente limitado ao pedido. Não inclua refatorações, melhorias ou mudanças extras. Liste somente arquivos realmente necessários. REGRAS DO AGENTE:\n${rules||"(nenhuma)"}`:`Você é o agente de programação do Lovable Decrypter v2. REGRA ABSOLUTA: altere SOMENTE o que foi solicitado. Preserve tudo que não for indispensável. Para update, content deve ser vazio e edits deve conter pares search/replace pequenos, exatos e únicos. Nunca reescreva arquivo inteiro. Arquivo novo pode usar content completo. Delete somente se explicitamente solicitado. Anexos são contexto e não devem ser adicionados ao repositório salvo pedido explícito. REGRAS DO AGENTE:\n${rules||"(nenhuma)"}`;
    let text=`PEDIDO DO USUÁRIO:\n${command.slice(0,50000)}\n\nPLANO APROVADO (se existir, escopo autoritativo):\n${approved?compact(approved,400000):"Nenhum"}\n\nCONTEXTO DO PROJETO:\n${compact(ctx)}`;
    let raw:any,res:Response;
    if(provider===LOCAL_PROVIDER){text+=localAttachmentBlock(attachments);const cfg=localConfig();const maxTokens=Math.max(1024,Math.min(32768,Number(body.max_output_tokens||16384)));res=await fetch(`${cfg.url}/v1/chat/completions`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${cfg.token}`},body:JSON.stringify({model:cfg.servedModel,messages:[{role:"system",content:system},{role:"user",content:text}],temperature:0.1,max_tokens:maxTokens,stream:false,response_format:{type:"json_schema",json_schema:{name:mode==="plan"?"decrypter_plan":"decrypter_build",strict:true,schema:mode==="plan"?PLAN_SCHEMA:EDIT_SCHEMA}}})});raw=await res.json().catch(()=>({}));}else{const input:any[]=[{type:"text",text},...media(attachments)];res=await fetch("https://generativelanguage.googleapis.com/v1beta/interactions",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":geminiKey},body:JSON.stringify({model,input,system_instruction:system,response_format:{type:"text",mime_type:"application/json",schema:mode==="plan"?PLAN_SCHEMA:EDIT_SCHEMA},store:false,generation_config:{max_output_tokens:Math.max(1024,Math.min(32768,Number(body.max_output_tokens||16384)))}})});raw=await res.json().catch(()=>({}));}
    if(!res.ok){const prefix=provider===LOCAL_PROVIDER?"LOCAL":"GEMINI";if(logId)await sb.from("ld_command_logs").update({status:"failed",duration_ms:Date.now()-started,error_code:`${prefix}_HTTP_${res.status}`}).eq("id",logId);await sb.rpc("ld_complete_command",{p_license_id:license.id,p_command_id:commandId,p_success:false,p_error_code:`${prefix}_HTTP_${res.status}`});return json({ok:false,code:`${prefix}_ERROR`,status:res.status,error:raw?.error?.message||raw?.message||`Falha no executor ${provider}`,provider,command_id:commandId,entitlement:reservation},res.status>=500?502:400);}
    if(provider==="gemini"&&raw?.status&&raw.status!=="completed"){if(logId)await sb.from("ld_command_logs").update({status:"failed",duration_ms:Date.now()-started,error_code:"GEMINI_"+String(raw.status).toUpperCase()}).eq("id",logId);await sb.rpc("ld_complete_command",{p_license_id:license.id,p_command_id:commandId,p_success:false,p_error_code:"GEMINI_INCOMPLETE"});return json({ok:false,code:"GEMINI_INCOMPLETE",gemini_status:raw.status,command_id:commandId,entitlement:reservation},422);}
    const outputText=provider===LOCAL_PROVIDER?extractLocal(raw):extractGemini(raw);let result:any;try{result=JSON.parse(stripJsonFence(outputText));}catch{if(logId)await sb.from("ld_command_logs").update({status:"failed",duration_ms:Date.now()-started,error_code:"INVALID_MODEL_JSON"}).eq("id",logId);await sb.rpc("ld_complete_command",{p_license_id:license.id,p_command_id:commandId,p_success:false,p_error_code:"INVALID_MODEL_JSON"});return json({ok:false,code:"INVALID_MODEL_JSON",provider,command_id:commandId,entitlement:reservation},502);}
    if(mode==="build"){const check=validateBuild(result,ctx,command);if(!check.ok){if(logId)await sb.from("ld_command_logs").update({status:"blocked",duration_ms:Date.now()-started,error_code:check.code}).eq("id",logId);await sb.rpc("ld_complete_command",{p_license_id:license.id,p_command_id:commandId,p_success:false,p_error_code:check.code});return json({ok:false,code:check.code,path:(check as any).path||null,provider,command_id:commandId,entitlement:reservation},422);}}
    const usage=telemetry(provider,raw);result.telemetry=usage;result.execution={provider,model,runtime:provider===LOCAL_PROVIDER?"decrypter-local/v1":"gemini-interactions",duration_ms:Date.now()-started};if(logId)await sb.from("ld_command_logs").update({status:"completed",duration_ms:Date.now()-started}).eq("id",logId);await sb.rpc("ld_complete_command",{p_license_id:license.id,p_command_id:commandId,p_success:true,p_error_code:null});return json({ok:true,mode,provider,model,gemini_billing_mode:provider==="gemini"?billingMode:null,command_id:commandId,interaction_id:raw?.id||null,duration_ms:Date.now()-started,usage,entitlement:reservation,result});
  }catch(e){console.error("ld-command",e);if(sb&&licenseId&&commandId){try{await sb.rpc("ld_complete_command",{p_license_id:licenseId,p_command_id:commandId,p_success:false,p_error_code:"INTERNAL_ERROR"});}catch{}}return json({ok:false,code:"INTERNAL_ERROR",command_id:commandId},500);}
});
