import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createSandboxDescriptor,buildSandboxMaterialization,normalizeSandboxDiff,assertSandboxDiffBinding,transitionSandbox,canonicalSandboxPath} from '../core/agent-sandbox.js';
const read=p=>fs.readFileSync(p,'utf8');
const manifest=JSON.parse(read('manifest.json'));
const pkg=JSON.parse(read('release/runtime-package.json'));
const settings=read('settings/config.js');
const core=read('core/agent-sandbox.js');
const runtime=read('background/agent-sandbox-runtime.js');
const client=read('content/agent-sandbox-client.js');
const entry=read('background/service-worker-entry.js');
const roadmap=read('docs/ROADMAP_V2_6_LOCAL_FIRST_AI.md');
assert.equal(manifest.version,'2.6.73');
assert.match(manifest.version_name,/Build 73 · Agent Sandbox \/ Shadow Worktree/);
assert.equal(pkg.candidate,manifest.version);
assert.ok(settings.includes("VERSION = '2.6.73'"));
assert.ok(settings.includes("AGENT_SANDBOX_SCHEMA = 'ld-agent-sandbox/1'"));

const sandbox=createSandboxDescriptor({taskId:'task-1',runtimeId:'codex-cli',baseHeadSha:'abc123',projectId:'p1'});
assert.equal(sandbox.isolation.authoritativeWrite,false);
assert.equal(sandbox.isolation.gitCredentials,false);
assert.equal(sandbox.isolation.providerCredentials,false);
assert.equal(sandbox.isolation.physicalWorktree,'bridge-required');
assert.equal(sandbox.authority.writeAuthority,false);

for(const bad of ['../secret','/etc/passwd','.git/config','.env','src/../../x','C:\\temp\\x'])assert.throws(()=>canonicalSandboxPath(bad));
for(const entry of [{path:'src/link',kind:'symlink'},{path:'src/hard',kind:'file',linkCount:2},{path:'src/junction',kind:'junction'},{path:'src/link2',symlinkTarget:'../outside'}])assert.throws(()=>buildSandboxMaterialization({sandbox,files:[entry]}));
const materialized=buildSandboxMaterialization({sandbox,files:[{path:'src/App.tsx',kind:'file',content:'export default 1;'}]});
assert.equal(materialized.authoritativeCredentialsIncluded,false);
assert.equal(materialized.readOnlySource,true);

const running=transitionSandbox(sandbox,'running');
const diff=await normalizeSandboxDiff({sandbox:running,taskId:'task-1',runtimeId:'codex-cli',baseHeadSha:'abc123',changes:[{action:'update',path:'src/App.tsx',content:'export default 2;'},{action:'create',path:'src/new.ts',content:'export const x=1;'}]});
assert.equal(diff.proposalDigest.length,64);
assert.equal(diff.writeAuthority,false);
assert.equal(diff.requiresFreshScopeEvaluation,true);
assert.equal(assertSandboxDiffBinding(diff,{sandboxId:sandbox.id,taskId:'task-1',runtimeId:'codex-cli',baseHeadSha:'abc123'}),diff);
await assert.rejects(normalizeSandboxDiff({sandbox:running,taskId:'other',runtimeId:'codex-cli',baseHeadSha:'abc123',changes:[{action:'update',path:'src/App.tsx',content:'x'}]}),e=>e?.code==='SANDBOX_TASK_MISMATCH');
await assert.rejects(normalizeSandboxDiff({sandbox:running,taskId:'task-1',runtimeId:'aider',baseHeadSha:'abc123',changes:[{action:'update',path:'src/App.tsx',content:'x'}]}),e=>e?.code==='SANDBOX_RUNTIME_MISMATCH');
await assert.rejects(normalizeSandboxDiff({sandbox:running,taskId:'task-1',runtimeId:'codex-cli',baseHeadSha:'stale',changes:[{action:'update',path:'src/App.tsx',content:'x'}]}),e=>e?.code==='SANDBOX_BASE_HEAD_MISMATCH');
await assert.rejects(normalizeSandboxDiff({sandbox:running,taskId:'task-1',runtimeId:'codex-cli',baseHeadSha:'abc123',changes:[{action:'create',path:'.env',content:'x'}]}));
await assert.rejects(normalizeSandboxDiff({sandbox:running,taskId:'task-1',runtimeId:'codex-cli',baseHeadSha:'abc123',changes:[{action:'update',path:'src/link',kind:'symlink',content:'x'}]}),e=>e?.code==='SANDBOX_DIFF_SPECIAL_FILE_FORBIDDEN');
assert.equal(transitionSandbox(running,'sealed').status,'sealed');
assert.throws(()=>transitionSandbox(sandbox,'sealed'),e=>e?.code==='SANDBOX_STATE_TRANSITION_INVALID');

for(const token of ['SANDBOX_PATH_INVALID','SANDBOX_SENSITIVE_PATH','SANDBOX_LINK_OR_SPECIAL_FILE_FORBIDDEN','SANDBOX_HARDLINK_FORBIDDEN','SANDBOX_BASE_HEAD_MISMATCH','proposalOnly:true','writeAuthority:false','gitCredentials:false','providerCredentials:false'])assert.ok(core.includes(token),token);
for(const token of ["PORT_NAME='ld2-agent-sandbox'","SESSION_KEY='ld73_agent_sandboxes_v1'",'chrome.storage.session','rawFileContentPersisted:false',"physicalWorktree:'bridge-required'",'gitCredentials:false','providerCredentials:false'])assert.ok(runtime.includes(token),token);
assert.ok(!runtime.includes('chrome.storage.local'));
assert.ok(entry.includes('installAgentSandboxRuntime();'));
assert.ok(client.includes('ld2-agent-sandbox'));
assert.ok(manifest.content_scripts.some(item=>(item.js||[]).includes('content/agent-sandbox-client.js')));
assert.match(pkg.notes,/Agent Sandbox \/ Shadow Worktree/);
assert.match(pkg.notes,/GitHub App \+ Supabase OAuth/);
assert.match(pkg.notes,/No OTA metadata, GitHub Release or store publication is authorized/);
assert.match(roadmap,/Build 73 — Agent Sandbox \/ Shadow Worktree/);
assert.match(roadmap,/Build 74 — Multi-Agent Runtime UI \+ Native Sessions/);
console.log('Build73 Agent Sandbox / Shadow Worktree contract OK');
