import fs from 'node:fs';
const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));
const pkg=JSON.parse(fs.readFileSync('release/runtime-package.json','utf8'));
const js=fs.readFileSync('ui/integrations-v49.js','utf8');
const css=fs.readFileSync('ui/integrations-v49.css','utf8');
const settings=fs.readFileSync('settings/config.js','utf8');
const app=manifest.content_scripts.find(x=>x.js?.includes('ui/integrations-v49.js'));
const parts=v=>String(v).split('.').map(Number);const atLeast=(v,f)=>{const a=parts(v),b=parts(f);for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]||0,y=b[i]||0;if(x!==y)return x>y;}return true;};
if(!app) throw new Error('Build49 integrations missing');
if(!atLeast(manifest.version,'2.5.49')||pkg.candidate!==manifest.version||!settings.includes(`VERSION = '${manifest.version}'`)) throw new Error('Build49 cumulative version mismatch');
if(app.js.indexOf('ui/integrations-v49.js')<=app.js.indexOf('ui/ui-kernel-v48.js')) throw new Error('integrations must register after UI kernel');
for(const id of ['github','github-sync','supabase','lovable','lovable-new-project','gemini']) if(!js.includes(`register('${id}'`)) throw new Error(`missing provider ${id}`);
if(js.includes("'popup,width")||js.includes('popup,width')) throw new Error('popup OAuth flow returned');
if(!js.includes("window.open(url, '_blank'")) throw new Error('persistent authorization tab missing');
if(!js.includes("pollUntil('github'")||!js.includes("pollUntil('supabase'")) throw new Error('OAuth reconciliation polling missing');
if(js.includes('data-settings')||js.includes('modalSettings(')) throw new Error('legacy settings modal dependency returned');
if(js.includes('.click(')) throw new Error('hidden DOM click delegation in integrations');
if(!settings.includes("merged.gemini.billingMode='free'")&&!settings.includes("merged.gemini.billingMode = 'free'")) throw new Error('free-only normalization missing');
if(!settings.includes('merged.gemini.zeroCost=true')&&!settings.includes('merged.gemini.zeroCost = true')) throw new Error('zero-cost normalization missing');
if(settings.includes("billingMode = merged.gemini.billingMode === 'user_paid'")) throw new Error('paid billing normalization still enabled');
if(!css.includes('backdrop-filter:blur(30px)')) throw new Error('integration glass surface missing');
console.log('Build49 integrations cumulative contract OK');
