import { createClient } from "jsr:@supabase/supabase-js@2.112.4";

const PUBLIC_SPKI_B64="MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/suDKmZG7B52xCVkCooS5MZfvVu+GjYTIfeOvlfi9tz29TQNN4uea318Nn2xf5uf/cm0bpaCADPwkqWSZV2MIA==";
export const API_BASE="https://api.supabase.com/v1";
const enc=new TextEncoder(),dec=new TextDecoder();
function b64d(v:string){const s=v.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(v.length/4)*4,"=");return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function sha(v:string){const d=await crypto.subtle.digest("SHA-256",enc.encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function backendKey(){const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){try{const p=JSON.parse(raw);if(p?.default)return String(p.default);const f=Object.values(p||{})[0];if(f)return String(f)}catch(_){}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||""}
export function admin(){const url=Deno.env.get("SUPABASE_URL")||"",key=backendKey();if(!url||!key)throw new Error("BACKEND_NOT_CONFIGURED");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function pub(){const der=Uint8Array.from(atob(PUBLIC_SPKI_B64),c=>c.charCodeAt(0));return crypto.subtle.importKey("spki",der,{name:"ECDSA",namedCurve:"P-256"},false,["verify"])}
async function signed(token:string){const[p,b,s]=token.trim().split(".");if(p!=="LD2"||!b||!s)throw new Error("KEY_INVALID_FORMAT");if(!await crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},await pub(),b64d(s),enc.encode(b)))throw new Error("KEY_INVALID_SIGNATURE");const x=JSON.parse(dec.decode(b64d(b)));if(x?.aud!=="lovable-decrypter"||Number(x?.v)!==1||!x?.license_id)throw new Error("KEY_INVALID_PAYLOAD");return x}
export async function authorize(req:Request,sb:any){const bearer=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim(),token=String(req.headers.get("x-license-key")||bearer||"").trim(),deviceId=String(req.headers.get("x-device-id")||"").trim();if(!token)throw new Error("KEY_REQUIRED");if(!deviceId)throw new Error("DEVICE_REQUIRED");const st=await signed(token);const{data:l,error}=await sb.from("ld_license_keys").select("id,status,expires_at,credit_balance,credit_debt").eq("id",String(st.license_id)).eq("key_hash",await sha(token)).maybeSingle();if(error)throw new Error("DB_ERROR");if(!l)throw new Error("KEY_NOT_REGISTERED");if(l.status!=="active")throw new Error(`KEY_${String(l.status).toUpperCase()}`);const active=Boolean(l.expires_at&&Date.parse(l.expires_at)>Date.now()),credit=!active&&Number(l.credit_debt||0)===0&&Number(l.credit_balance||0)>0;if(!active&&!credit)throw new Error("ENTITLEMENT_EXHAUSTED");const deviceHash=await sha(deviceId);const{data:d,error:de}=await sb.from("ld_license_devices").select("id,revoked_at").eq("license_id",l.id).eq("device_hash",deviceHash).maybeSingle();if(de)throw new Error("DB_ERROR");if(!d)throw new Error("DEVICE_NOT_BOUND");if(d.revoked_at)throw new Error("DEVICE_REVOKED");return{licenseId:String(l.id),deviceHash}}
export async function getSecret(sb:any,name:string){const{data,error}=await sb.rpc("ld_backend_secret",{p_name:name});if(error||!data)throw new Error(`SECRET_MISSING:${name}`);return String(data)}
async function setSecret(sb:any,name:string,value:string){const{error}=await sb.rpc("ld_backend_secret_set",{p_name:name,p_value:value,p_description:"Lovable Decrypter Supabase OAuth refresh token"});if(error)throw new Error(`SECRET_STORE_FAILED:${name}`)}
function basic(id:string,secret:string){return`Basic ${btoa(`${id}:${secret}`)}`}
export async function session(sb:any,a:any){const[{data:cfg,error:ce},{data:conn,error:xe}]=await Promise.all([sb.from("ld_supabase_oauth_config").select("*").eq("singleton",true).maybeSingle(),sb.from("ld_supabase_connections").select("*").eq("license_id",a.licenseId).eq("device_hash",a.deviceHash).maybeSingle()]);if(ce||!cfg)throw new Error("SUPABASE_OAUTH_APP_NOT_CONFIGURED");if(xe||!conn)throw new Error("SUPABASE_NOT_CONNECTED");const refresh=await getSecret(sb,String(conn.refresh_secret_name)),secret=await getSecret(sb,"LD_SUPABASE_OAUTH_CLIENT_SECRET");const res=await fetch(`${API_BASE}/oauth/token`,{method:"POST",headers:{Authorization:basic(String(cfg.client_id),secret),"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:refresh})});const data=await res.json().catch(()=>null);if(!res.ok||!data?.access_token)throw new Error(`TOKEN_REFRESH_FAILED:${res.status}`);if(data.refresh_token&&String(data.refresh_token)!==refresh)await setSecret(sb,String(conn.refresh_secret_name),String(data.refresh_token));return{token:String(data.access_token),scope:String(data.scope||conn.granted_scope||"")}}
export function missing(scope:string,required:string[]){const got=new Set(String(scope||"").split(/[\s,]+/).filter(Boolean));return required.filter(x=>!got.has(x))}
export async function management(token:string,path:string,options:RequestInit={}){const res=await fetch(`${API_BASE}${path}`,{...options,headers:{Authorization:`Bearer ${token}`,Accept:"application/json",...(options.headers||{})}});const raw=await res.text().catch(()=>"");let data:any=null;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!res.ok)throw new Error(`SUPABASE_MANAGEMENT_HTTP_${res.status}:${data?.message||data?.error||"request failed"}`);return data}
export async function query(token:string,ref:string,sql:string){return management(token,`/projects/${encodeURIComponent(ref)}/database/query`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:sql})})}
export async function job(sb:any,id:string,a:any){const{data,error}=await sb.from("ld_cloud_asset_jobs").select("*").eq("id",id).eq("license_id",a.licenseId).eq("device_hash",a.deviceHash).maybeSingle();if(error)throw new Error("ASSET_JOB_READ_FAILED");if(!data)throw new Error("ASSET_JOB_NOT_FOUND");return data}
export async function save(sb:any,j:any,patch:any,message=""){const logs=Array.isArray(j.logs)?[...j.logs]:[];if(message)logs.push({at:new Date().toISOString(),level:"info",message:String(message).slice(0,900)});const{data,error}=await sb.from("ld_cloud_asset_jobs").update({...patch,logs:logs.slice(-120),updated_at:new Date().toISOString()}).eq("id",j.id).select("*").single();if(error)throw new Error("ASSET_JOB_UPDATE_FAILED");return data}
export function safeJob(j:any){if(!j)return null;const{device_hash,handoff_token_hash,source_db_secret_name,source_url_secret_name,source_key_secret_name,...x}=j;return x}
