import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';

const ADMIN_SECRET='LD_KNOWLEDGE_ADMIN_TOKEN';
const MODEL='gte-small';
const MAX_RAW=900000, MAX_TEXT=72000, MAX_CHUNKS=8, TARGET=3200, OVERLAP=320;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-knowledge-admin-token','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const enc=new TextEncoder();
async function sha(v:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function entities(v:string){return v.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)||32)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)||32));}
function plain(raw:string,type:string){
  if(!/html/i.test(type))return raw.replace(/\r\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim().slice(0,MAX_TEXT);
  const main=raw.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1]||raw;
  return entities(main.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi,' ').replace(/<nav\b[^>]*>[\s\S]*?<\/nav>/gi,' ').replace(/<footer\b[^>]*>[\s\S]*?<\/footer>/gi,' ').replace(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi,'\n# $1\n').replace(/<h2\b[^>]*>([\s\S]*?)<\/h2>/gi,'\n## $1\n').replace(/<h3\b[^>]*>([\s\S]*?)<\/h3>/gi,'\n### $1\n').replace(/<(br|\/p|\/li|\/div|\/section|\/article)>/gi,'\n').replace(/<li\b[^>]*>/gi,'\n- ').replace(/<pre\b[^>]*>/gi,'\n```\n').replace(/<\/pre>/gi,'\n```\n').replace(/<code\b[^>]*>/gi,'`').replace(/<\/code>/gi,'`').replace(/<[^>]+>/g,' ')).replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim().slice(0,MAX_TEXT);
}
function classify(u:URL){if(u.protocol!=='https:')throw new Error('SOURCE_HTTPS_REQUIRED');const h=u.hostname.toLowerCase();if(h==='docs.lovable.dev')return{domain:h,category:'lovable'};if(h==='docs.github.com')return{domain:h,category:'github'};if(h==='supabase.com'&&u.pathname.startsWith('/docs/'))return{domain:h,category:'supabase'};throw new Error('SOURCE_NOT_ALLOWLISTED');}
function title(raw:string,type:string,u:URL){if(/html/i.test(type)){const m=raw.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i);if(m)return entities(m[1].replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim().slice(0,240);}const h=raw.match(/^#\s+(.+)$/m);return (h?.[1]||u.pathname.split('/').filter(Boolean).pop()||u.hostname).slice(0,240);}
function chunks(text:string){const blocks=text.split(/\n{2,}/).map(x=>x.trim()).filter(x=>x.length>=20),out:any[]=[];let cur='',heads:string[]=[];for(const block of blocks){const h=block.match(/^(#{1,4})\s+(.+)$/);if(h)heads=[...heads.slice(0,Math.max(0,h[1].length-1)),h[2].trim()].slice(0,4);if(cur&&cur.length+block.length+2>TARGET){out.push({content:cur.trim(),headings:[...heads]});cur=cur.slice(Math.max(0,cur.length-OVERLAP))+'\n\n'+block;}else cur+=(cur?'\n\n':'')+block;if(out.length>=MAX_CHUNKS)break;}if(cur.trim().length>=80&&out.length<MAX_CHUNKS)out.push({content:cur.trim(),headings:[...heads]});return out.slice(0,MAX_CHUNKS);}
function vector(raw:any){const v=raw?.data??raw,a=Array.isArray(v)?v:(v&&typeof v[Symbol.iterator]==='function'?Array.from(v):[]),out=a.map(Number).filter(Number.isFinite);if(out.length!==384)throw new Error(`EMBEDDING_DIMENSION_${out.length}`);return out;}
async function admin(req:Request,sb:any){const got=String(req.headers.get('x-knowledge-admin-token')||'').trim();if(!got)throw new Error('ADMIN_TOKEN_REQUIRED');const{data:expected,error}=await sb.rpc('ld_backend_secret',{p_name:ADMIN_SECRET});if(error||!expected)throw new Error('ADMIN_SECRET_UNAVAILABLE');if(await sha(got)!==await sha(String(expected)))throw new Error('ADMIN_TOKEN_INVALID');}
async function embed(list:any[]){const model=new Supabase.ai.Session(MODEL),rows=[];for(let i=0;i<list.length;i++){const c=list[i],raw=await model.run(c.content,{mean_pool:true,normalize:true});rows.push({chunk_index:i,heading_path:c.headings,content:c.content,content_sha256:await sha(c.content),token_estimate:Math.ceil(c.content.length/4),embedding:JSON.stringify(vector(raw)),metadata:{embedding_model:MODEL,source:'official_docs'}});}return rows;}
async function ingest(sb:any,rawUrl:string){const requested=new URL(String(rawUrl||'').trim()),kind=classify(requested),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);let r:Response;try{r=await fetch(requested.toString(),{headers:{'user-agent':'Lovable-Decrypter-Knowledge/2.4.16','accept':'text/markdown,text/plain;q=0.9,text/html;q=0.5'},redirect:'follow',signal:ctl.signal});}finally{clearTimeout(timer);}if(!r.ok)throw new Error(`SOURCE_HTTP_${r.status}`);const resolved=new URL(r.url||requested.toString()),resolvedKind=classify(resolved);if(resolvedKind.category!==kind.category)throw new Error('SOURCE_REDIRECT_CATEGORY_CHANGED');const type=String(r.headers.get('content-type')||'text/plain'),raw=await r.text();if(!raw||raw.length>MAX_RAW)throw new Error('SOURCE_SIZE_INVALID');const text=plain(raw,type);if(text.length<200)throw new Error('SOURCE_CONTENT_TOO_SMALL');const parts=chunks(text);if(!parts.length)throw new Error('SOURCE_NO_CHUNKS');const rows=await embed(parts),canonical=resolved.toString().split('#')[0],key=`${kind.category}:${(await sha(canonical)).slice(0,24)}`,now=new Date().toISOString();const{data:source,error}=await sb.from('ld_knowledge_sources').upsert({source_key:key,canonical_url:canonical,domain:kind.domain,category:kind.category,title:title(raw,type,resolved),source_type:'official_docs',status:'active',content_sha256:await sha(text),fetched_at:now,updated_at:now,metadata:{content_type:type,embedding_model:MODEL,truncated:text.length>=MAX_TEXT,max_chunks:MAX_CHUNKS}},{onConflict:'canonical_url'}).select('id,source_key,title,canonical_url,category').single();if(error||!source)throw new Error('SOURCE_UPSERT_FAILED');const{error:del}=await sb.from('ld_knowledge_chunks').delete().eq('source_id',source.id);if(del)throw new Error('CHUNK_REPLACE_FAILED');const{error:ins}=await sb.from('ld_knowledge_chunks').insert(rows.map(x=>({...x,source_id:source.id,updated_at:now})));if(ins)throw new Error('CHUNK_INSERT_FAILED');return{...source,chunks:rows.length};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);try{const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!service)return json({ok:false,code:'BACKEND_NOT_CONFIGURED'},503);const sb=createClient(url,service,{auth:{persistSession:false}});await admin(req,sb);const body=await req.json().catch(()=>({})),action=String(body.action||'status');if(action==='status'){const[{count:sources},{count:chunks}]=await Promise.all([sb.from('ld_knowledge_sources').select('*',{count:'exact',head:true}).eq('status','active'),sb.from('ld_knowledge_chunks').select('*',{count:'exact',head:true})]);return json({ok:true,schema:'ld-knowledge/1',embedding_model:MODEL,sources:sources||0,chunks:chunks||0});}if(action==='ingest_url')return json({ok:true,result:await ingest(sb,String(body.url||''))});if(action==='disable_url'){const u=new URL(String(body.url||'').trim());classify(u);const{error}=await sb.from('ld_knowledge_sources').update({status:'disabled',updated_at:new Date().toISOString()}).eq('canonical_url',u.toString().split('#')[0]);if(error)throw new Error('SOURCE_DISABLE_FAILED');return json({ok:true});}return json({ok:false,code:'UNKNOWN_ACTION'},400);}catch(e){const code=String((e as Error)?.message||'INTERNAL_ERROR');console.error('ld-knowledge-ingest',code);return json({ok:false,code},/^ADMIN_/.test(code)?403:500);}});
