import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';

const ADMIN_SECRET='LD_KNOWLEDGE_ADMIN_TOKEN';
const MAX_RAW=900000,MAX_TEXT=96000,MAX_CHUNKS=16,TARGET=3400,OVERLAP=360;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-knowledge-admin-token','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const enc=new TextEncoder();
async function sha(v:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function admin(req:Request,sb:any){const got=String(req.headers.get('x-knowledge-admin-token')||'').trim();if(!got)throw new Error('ADMIN_TOKEN_REQUIRED');const{data:want,error}=await sb.rpc('ld_backend_secret',{p_name:ADMIN_SECRET});if(error||!want)throw new Error('ADMIN_SECRET_UNAVAILABLE');if(await sha(got)!==await sha(String(want)))throw new Error('ADMIN_TOKEN_INVALID');}
function entities(v:string){return v.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n)||32)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16)||32));}
function classify(u:URL){if(u.protocol!=='https:')throw new Error('SOURCE_HTTPS_REQUIRED');const h=u.hostname.toLowerCase();if(h==='docs.lovable.dev')return{domain:h,category:'lovable'};if(h==='docs.github.com')return{domain:h,category:'github'};if(h==='supabase.com'&&u.pathname.startsWith('/docs/'))return{domain:h,category:'supabase'};throw new Error('SOURCE_NOT_ALLOWLISTED');}
function text(raw:string,type:string){if(!/html/i.test(type))return raw.replace(/\r\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim().slice(0,MAX_TEXT);const main=raw.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1]||raw;return entities(main.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi,' ').replace(/<nav\b[^>]*>[\s\S]*?<\/nav>/gi,' ').replace(/<footer\b[^>]*>[\s\S]*?<\/footer>/gi,' ').replace(/<h1\b[^>]*>([\s\S]*?)<\/h1>/gi,'\n# $1\n').replace(/<h2\b[^>]*>([\s\S]*?)<\/h2>/gi,'\n## $1\n').replace(/<h3\b[^>]*>([\s\S]*?)<\/h3>/gi,'\n### $1\n').replace(/<(br|\/p|\/li|\/div|\/section|\/article)>/gi,'\n').replace(/<li\b[^>]*>/gi,'\n- ').replace(/<pre\b[^>]*>/gi,'\n```\n').replace(/<\/pre>/gi,'\n```\n').replace(/<code\b[^>]*>/gi,'`').replace(/<\/code>/gi,'`').replace(/<[^>]+>/g,' ')).replace(/[ \t]+/g,' ').replace(/ *\n */g,'\n').replace(/\n{3,}/g,'\n\n').trim().slice(0,MAX_TEXT);}
function title(raw:string,type:string,u:URL){if(/html/i.test(type)){const m=raw.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i);if(m)return entities(m[1].replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim().slice(0,240);}return(raw.match(/^#\s+(.+)$/m)?.[1]||u.pathname.split('/').filter(Boolean).pop()||u.hostname).slice(0,240);}
function chunks(input:string){const blocks=input.split(/\n{2,}/).map(x=>x.trim()).filter(x=>x.length>=20),out:any[]=[];let cur='',heads:string[]=[];for(const b of blocks){const h=b.match(/^(#{1,4})\s+(.+)$/);if(h)heads=[...heads.slice(0,Math.max(0,h[1].length-1)),h[2].trim()].slice(0,4);if(cur&&cur.length+b.length+2>TARGET){out.push({content:cur.trim(),heading_path:[...heads]});cur=cur.slice(Math.max(0,cur.length-OVERLAP))+'\n\n'+b;}else cur+=(cur?'\n\n':'')+b;if(out.length>=MAX_CHUNKS)break;}if(cur.trim().length>=80&&out.length<MAX_CHUNKS)out.push({content:cur.trim(),heading_path:[...heads]});return out.slice(0,MAX_CHUNKS);}
async function ingest(sb:any,value:string){const requested=new URL(String(value||'').trim()),kind=classify(requested),ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);let r:Response;try{r=await fetch(requested.toString(),{headers:{'user-agent':'Lovable-Decrypter-Knowledge/2.4.16','accept':'text/markdown,text/plain;q=0.9,text/html;q=0.5'},redirect:'follow',signal:ctl.signal});}finally{clearTimeout(timer);}if(!r.ok)throw new Error(`SOURCE_HTTP_${r.status}`);const resolved=new URL(r.url||requested.toString()),resolvedKind=classify(resolved);if(resolvedKind.category!==kind.category)throw new Error('SOURCE_REDIRECT_CATEGORY_CHANGED');const type=String(r.headers.get('content-type')||'text/plain'),raw=await r.text();if(!raw||raw.length>MAX_RAW)throw new Error('SOURCE_SIZE_INVALID');const normalized=text(raw,type);if(normalized.length<200)throw new Error('SOURCE_CONTENT_TOO_SMALL');const pageHash=await sha(normalized),canonical=resolved.toString().split('#')[0],parts=chunks(normalized);if(!parts.length)throw new Error('SOURCE_NO_CHUNKS');const{data:existing}=await sb.from('ld_knowledge_sources').select('id,content_sha256').eq('canonical_url',canonical).maybeSingle();if(existing?.content_sha256===pageHash){const{count}=await sb.from('ld_knowledge_chunks').select('*',{count:'exact',head:true}).eq('source_id',existing.id);return{id:existing.id,canonical_url:canonical,category:kind.category,chunks:count||0,unchanged:true};}const now=new Date().toISOString(),key=`${kind.category}:${(await sha(canonical)).slice(0,24)}`;const{data:source,error}=await sb.from('ld_knowledge_sources').upsert({source_key:key,canonical_url:canonical,domain:kind.domain,category:kind.category,title:title(raw,type,resolved),source_type:'official_docs',status:'active',content_sha256:pageHash,fetched_at:now,updated_at:now,metadata:{content_type:type,embedding_model:'gte-small',pipeline:'staged-v1'}},{onConflict:'canonical_url'}).select('id,source_key,title,canonical_url,category').single();if(error||!source)throw new Error('SOURCE_UPSERT_FAILED');const{error:del}=await sb.from('ld_knowledge_chunks').delete().eq('source_id',source.id);if(del)throw new Error('CHUNK_REPLACE_FAILED');const rows=[];for(let i=0;i<parts.length;i++)rows.push({source_id:source.id,chunk_index:i,heading_path:parts[i].heading_path,content:parts[i].content,content_sha256:await sha(parts[i].content),token_estimate:Math.ceil(parts[i].content.length/4),embedding:null,embedding_status:'pending',embedding_error:'',metadata:{embedding_model:'gte-small',source:'official_docs'},updated_at:now});const{error:ins}=await sb.from('ld_knowledge_chunks').insert(rows);if(ins)throw new Error('CHUNK_INSERT_FAILED');return{...source,chunks:rows.length,pending:rows.length,unchanged:false};}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);try{const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!service)return json({ok:false,code:'BACKEND_NOT_CONFIGURED'},503);const sb=createClient(url,service,{auth:{persistSession:false}});await admin(req,sb);const body=await req.json().catch(()=>({})),action=String(body.action||'status');if(action==='status'){const[{count:sources},{count:ready},{count:pending},{count:failed}]=await Promise.all([sb.from('ld_knowledge_sources').select('*',{count:'exact',head:true}).eq('status','active'),sb.from('ld_knowledge_chunks').select('*',{count:'exact',head:true}).eq('embedding_status','ready'),sb.from('ld_knowledge_chunks').select('*',{count:'exact',head:true}).eq('embedding_status','pending'),sb.from('ld_knowledge_chunks').select('*',{count:'exact',head:true}).eq('embedding_status','failed')]);return json({ok:true,schema:'ld-knowledge/1',embedding_model:'gte-small',sources:sources||0,ready:ready||0,pending:pending||0,failed:failed||0});}if(action==='ingest_url')return json({ok:true,result:await ingest(sb,String(body.url||''))});return json({ok:false,code:'UNKNOWN_ACTION'},400);}catch(e){const code=String((e as Error)?.message||'INTERNAL_ERROR');console.error('ld-knowledge-ingest',code);return json({ok:false,code},/^ADMIN_/.test(code)?403:500);}});
