import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'jsr:@supabase/supabase-js@2';

const ADMIN_SECRET='LD_KNOWLEDGE_ADMIN_TOKEN';
const MODEL='gte-small';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-knowledge-admin-token','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
const enc=new TextEncoder();
async function sha(v:string){const d=await crypto.subtle.digest('SHA-256',enc.encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function admin(req:Request,sb:any){const got=String(req.headers.get('x-knowledge-admin-token')||'').trim();if(!got)throw new Error('ADMIN_TOKEN_REQUIRED');const{data:want,error}=await sb.rpc('ld_backend_secret',{p_name:ADMIN_SECRET});if(error||!want)throw new Error('ADMIN_SECRET_UNAVAILABLE');if(await sha(got)!==await sha(String(want)))throw new Error('ADMIN_TOKEN_INVALID');}
function vector(raw:any){const v=raw?.data??raw,a=Array.isArray(v)?v:(v&&typeof v[Symbol.iterator]==='function'?Array.from(v):[]),out=a.map(Number).filter(Number.isFinite);if(out.length!==384)throw new Error(`EMBEDDING_DIMENSION_${out.length}`);return out;}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return json({ok:false,code:'METHOD_NOT_ALLOWED'},405);try{const url=Deno.env.get('SUPABASE_URL'),service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!service)return json({ok:false,code:'BACKEND_NOT_CONFIGURED'},503);const sb=createClient(url,service,{auth:{persistSession:false}});await admin(req,sb);const body=await req.json().catch(()=>({})),limit=Math.max(1,Math.min(3,Number(body.limit||2)));const{data:claimed,error}=await sb.rpc('ld_claim_knowledge_chunks',{p_limit:limit});if(error)throw new Error('CLAIM_FAILED');const rows=Array.isArray(claimed)?claimed:[];if(!rows.length){const{count:pending}=await sb.from('ld_knowledge_chunks').select('*',{count:'exact',head:true}).in('embedding_status',['pending','failed']);return json({ok:true,processed:0,failed:0,pending:pending||0});}const model=new Supabase.ai.Session(MODEL);let processed=0,failed=0;for(const row of rows){try{const raw=await model.run(String(row.content||''),{mean_pool:true,normalize:true}),embedding=JSON.stringify(vector(raw));const{error:updateError}=await sb.from('ld_knowledge_chunks').update({embedding,embedding_status:'ready',embedding_error:'',updated_at:new Date().toISOString()}).eq('id',row.id);if(updateError)throw new Error('UPDATE_FAILED');processed++;}catch(e){failed++;await sb.from('ld_knowledge_chunks').update({embedding:null,embedding_status:'failed',embedding_error:String((e as Error)?.message||'EMBED_FAILED').slice(0,500),updated_at:new Date().toISOString()}).eq('id',row.id);}}const{count:pending}=await sb.from('ld_knowledge_chunks').select('*',{count:'exact',head:true}).in('embedding_status',['pending','failed']);return json({ok:true,model:MODEL,processed,failed,pending:pending||0});}catch(e){const code=String((e as Error)?.message||'INTERNAL_ERROR');console.error('ld-knowledge-embed',code);return json({ok:false,code},/^ADMIN_/.test(code)?403:500);}});
