import { createHash, randomBytes, randomUUID } from 'node:crypto';
import type { EventBus } from '@github-decrypter/shared';
import type { Capability, CapabilityRequirement } from './capability-security.js';
import type { LocalDatabase } from './database.js';
import { isDurableJobTerminalState, type DurableJobId, type DurableJobState } from './job-types.js';
import type { LocalRuntimeEventCatalog } from './lifecycle.js';

export const APPROVAL_STATES = ['pending', 'approved', 'denied', 'consumed', 'expired', 'cancelled'] as const;
export type ApprovalState = (typeof APPROVAL_STATES)[number];
export const APPROVAL_RECEIPT_PREFIX = 'gd_approval_v1_';
export const APPROVAL_MIN_TTL_MS = 1_000;
export const APPROVAL_MAX_TTL_MS = 24 * 60 * 60 * 1_000;

declare const approvalTransactionIdBrand: unique symbol;
declare const approvalReceiptBrand: unique symbol;
export type ApprovalTransactionId = string & { readonly [approvalTransactionIdBrand]: 'approval-transaction' };
export type ApprovalReceipt = string & { readonly [approvalReceiptBrand]: 'approval-receipt' };
export interface ApprovalRequirement extends CapabilityRequirement {}
export interface ApprovalTransactionRequest { readonly jobId: DurableJobId; readonly action: string; readonly summary: string; readonly requirements: readonly ApprovalRequirement[]; readonly payloadDigest: string; readonly ttlMs: number; }
export interface ApprovalDecisionRequest { readonly transactionId: ApprovalTransactionId; readonly actor: string; readonly reason?: string; }
export interface ApprovalTransactionRecord { readonly id: ApprovalTransactionId; readonly jobId: DurableJobId; readonly action: string; readonly summary: string; readonly requirements: readonly ApprovalRequirement[]; readonly payloadDigest: string; readonly state: ApprovalState; readonly requestedAt: string; readonly expiresAt: string; readonly decidedAt: string | null; readonly decidedBy: string | null; readonly decisionReason: string | null; readonly consumedAt: string | null; }
export interface ApprovedTransaction { readonly transaction: ApprovalTransactionRecord; readonly receipt: ApprovalReceipt; }
export interface ApprovalTransactionsStatus { readonly ready: boolean; readonly schemaVersion: number; readonly pending: number; readonly approved: number; readonly consumed: number; readonly denied: number; readonly expired: number; readonly cancelled: number; readonly oneShotReceipts: true; readonly plaintextReceiptPersistence: false; readonly externalDecisionTransport: false; }
export interface ApprovalTransactionsOptions { readonly database: LocalDatabase; readonly eventBus?: EventBus<LocalRuntimeEventCatalog>; readonly now?: () => string; }
interface ApprovalRow { readonly id: unknown; readonly job_id: unknown; readonly action: unknown; readonly summary: unknown; readonly requirements_json: unknown; readonly payload_digest: unknown; readonly state: unknown; readonly requested_at: unknown; readonly expires_at: unknown; readonly decided_at: unknown; readonly decided_by: unknown; readonly decision_reason: unknown; readonly consumed_at: unknown; }
interface StateCountRow { readonly state: unknown; readonly count: unknown; }
interface JobStateRow { readonly state: unknown; }

function text(value: unknown, label: string): string { if (typeof value !== 'string') throw new Error(`SQLite returned invalid text for ${label}.`); return value; }
function nullableText(value: unknown, label: string): string | null { return value === null ? null : text(value, label); }
function integer(value: unknown, label: string): number { const normalized = typeof value === 'bigint' ? Number(value) : value; if (!Number.isSafeInteger(normalized)) throw new Error(`SQLite returned invalid integer for ${label}.`); return normalized as number; }
function normalizeText(value: string, label: string, max: number): string { const normalized = value.trim(); if (!normalized) throw new TypeError(`${label} must be non-empty.`); if (normalized.length > max) throw new TypeError(`${label} may not exceed ${max} characters.`); return normalized; }
function normalizeDigest(value: string): string { const normalized = value.trim().toLowerCase(); if (!/^[a-f0-9]{64}$/.test(normalized)) throw new TypeError('payloadDigest must be a SHA-256 hex digest.'); return normalized; }
function normalizeResource(value: string): string { const normalized = value.trim(); if (!normalized.startsWith('gd://') || /\s|\*/.test(normalized)) throw new TypeError('Approval resources must be explicit gd:// resources without whitespace or wildcards.'); const parsed = new URL(normalized); if (parsed.protocol !== 'gd:' || !parsed.hostname || parsed.username || parsed.password || parsed.search || parsed.hash) throw new TypeError('Approval resources must be canonical gd:// resources.'); return normalized; }
function normalizeCapability(value: Capability): Capability { const allowed = ['READ','WRITE','EXECUTE','NETWORK','DATABASE_WRITE','GIT_WRITE','DESTRUCTIVE','SECRETS'] as const; if (!(allowed as readonly string[]).includes(value)) throw new TypeError(`Unsupported approval capability: ${String(value)}.`); return value; }
function normalizeRequirements(requirements: readonly ApprovalRequirement[]): readonly ApprovalRequirement[] { if (!requirements.length) throw new TypeError('Approval Transactions require at least one capability requirement.'); const unique = new Map<string, ApprovalRequirement>(); for (const requirement of requirements) { const normalized = Object.freeze({ capability: normalizeCapability(requirement.capability), resource: normalizeResource(requirement.resource) }); unique.set(`${normalized.capability}\u0000${normalized.resource}`, normalized); } return Object.freeze([...unique.values()]); }
function normalizeTtl(ttlMs: number): number { if (!Number.isSafeInteger(ttlMs) || ttlMs < APPROVAL_MIN_TTL_MS || ttlMs > APPROVAL_MAX_TTL_MS) throw new RangeError(`Approval ttlMs must be between ${APPROVAL_MIN_TTL_MS} and ${APPROVAL_MAX_TTL_MS}.`); return ttlMs; }
function createReceipt(): ApprovalReceipt { return `${APPROVAL_RECEIPT_PREFIX}${randomBytes(32).toString('base64url')}` as ApprovalReceipt; }
function validReceipt(value: unknown): value is ApprovalReceipt { return typeof value === 'string' && value.startsWith(APPROVAL_RECEIPT_PREFIX) && /^[A-Za-z0-9_-]{43}$/.test(value.slice(APPROVAL_RECEIPT_PREFIX.length)); }
function receiptHash(receipt: string): string { return createHash('sha256').update(receipt, 'utf8').digest('hex'); }

export class ApprovalTransactions {
  readonly #database: LocalDatabase; readonly #eventBus?: EventBus<LocalRuntimeEventCatalog>; readonly #now: () => string; #ready = false;
  constructor(options: ApprovalTransactionsOptions) { this.#database = options.database; this.#eventBus = options.eventBus; this.#now = options.now ?? (() => new Date().toISOString()); }
  status(): ApprovalTransactionsStatus { const schemaVersion = this.#database.status?.schemaVersion ?? 0; const counts = new Map<ApprovalState, number>(); if (this.#database.isOpen && schemaVersion >= 7) { for (const row of this.#database.read((database) => database.prepare('SELECT state, COUNT(*) AS count FROM gd_approval_transactions GROUP BY state').all() as unknown as StateCountRow[])) counts.set(text(row.state, 'approval state') as ApprovalState, integer(row.count, 'approval count')); } return Object.freeze({ ready: this.#ready, schemaVersion, pending: counts.get('pending') ?? 0, approved: counts.get('approved') ?? 0, consumed: counts.get('consumed') ?? 0, denied: counts.get('denied') ?? 0, expired: counts.get('expired') ?? 0, cancelled: counts.get('cancelled') ?? 0, oneShotReceipts: true, plaintextReceiptPersistence: false, externalDecisionTransport: false }); }
  async initialize(): Promise<ApprovalTransactionsStatus> { const schemaVersion = this.#database.status?.schemaVersion ?? 0; if (!this.#database.isOpen || schemaVersion < 7) throw new Error('Approval Transactions require Local Database schema 7 or newer.'); await this.expirePending(); this.#ready = true; const status = this.status(); await this.#eventBus?.publish('gd.local.approval.ready', { pending: status.pending, approved: status.approved, oneShotReceipts: true, plaintextReceiptPersistence: false, externalDecisionTransport: false }); return status; }
  async request(input: ApprovalTransactionRequest): Promise<ApprovalTransactionRecord> { this.#assertReady(); const action = normalizeText(input.action, 'action', 200); const summary = normalizeText(input.summary, 'summary', 2_000); const requirements = normalizeRequirements(input.requirements); const payloadDigest = normalizeDigest(input.payloadDigest); const ttlMs = normalizeTtl(input.ttlMs); this.#assertJobActive(input.jobId); const requestedAt = this.#now(); const requestedMs = Date.parse(requestedAt); if (!Number.isFinite(requestedMs)) throw new Error('Approval clock returned an invalid timestamp.'); const expiresAt = new Date(requestedMs + ttlMs).toISOString(); const id = `gd_approval_${randomUUID()}` as ApprovalTransactionId; this.#database.transaction((database) => database.prepare("INSERT INTO gd_approval_transactions (id, job_id, action, summary, requirements_json, payload_digest, state, requested_at, expires_at, decided_at, decided_by, decision_reason, receipt_hash, consumed_at) VALUES (?, ?, ?, ?, ?, ?, 'pending', ?, ?, NULL, NULL, NULL, NULL, NULL)").run(id, input.jobId, action, summary, JSON.stringify(requirements), payloadDigest, requestedAt, expiresAt)); const record = this.get(id); if (!record) throw new Error('Approval transaction disappeared after creation.'); await this.#eventBus?.publish('gd.local.approval.requested', { transactionId: id, jobId: input.jobId, action, expiresAt }); return record; }
  async approve(input: ApprovalDecisionRequest): Promise<ApprovedTransaction> { this.#assertReady(); const actor = normalizeText(input.actor, 'actor', 200); const reason = input.reason ? normalizeText(input.reason, 'reason', 2_000) : null; const current = this.#requirePending(input.transactionId); this.#assertJobActive(current.jobId); const now = this.#now(); if (Date.parse(current.expiresAt) <= Date.parse(now)) { await this.#expireOne(current.id, now); throw new Error('Approval transaction expired before approval.'); } const receipt = createReceipt(); const hash = receiptHash(receipt); this.#database.transaction((database) => { const result = database.prepare("UPDATE gd_approval_transactions SET state = 'approved', decided_at = ?, decided_by = ?, decision_reason = ?, receipt_hash = ? WHERE id = ? AND state = 'pending'").run(now, actor, reason, hash, current.id); if (Number(result.changes) !== 1) throw new Error('Approval transaction changed concurrently.'); }); const transaction = this.get(current.id); if (!transaction) throw new Error('Approved transaction disappeared.'); await this.#eventBus?.publish('gd.local.approval.decided', { transactionId: current.id, jobId: current.jobId, decision: 'approved', actor, occurredAt: now }); return Object.freeze({ transaction, receipt }); }
  async deny(input: ApprovalDecisionRequest): Promise<ApprovalTransactionRecord> { this.#assertReady(); const actor = normalizeText(input.actor, 'actor', 200); const reason = normalizeText(input.reason ?? 'denied', 'reason', 2_000); const current = this.#requirePending(input.transactionId); const now = this.#now(); this.#database.transaction((database) => { const result = database.prepare("UPDATE gd_approval_transactions SET state = 'denied', decided_at = ?, decided_by = ?, decision_reason = ?, receipt_hash = NULL WHERE id = ? AND state = 'pending'").run(now, actor, reason, current.id); if (Number(result.changes) !== 1) throw new Error('Approval transaction changed concurrently.'); }); const transaction = this.get(current.id)!; await this.#eventBus?.publish('gd.local.approval.decided', { transactionId: current.id, jobId: current.jobId, decision: 'denied', actor, occurredAt: now }); return transaction; }
  async cancel(transactionId: ApprovalTransactionId, reason = 'cancelled'): Promise<boolean> { this.#assertReady(); const current = this.get(transactionId); if (!current || current.state !== 'pending') return false; const now = this.#now(); const normalizedReason = normalizeText(reason, 'reason', 2_000); const changed = this.#database.transaction((database) => Number(database.prepare("UPDATE gd_approval_transactions SET state = 'cancelled', decided_at = ?, decision_reason = ?, receipt_hash = NULL WHERE id = ? AND state = 'pending'").run(now, normalizedReason, transactionId).changes) === 1); if (changed) await this.#eventBus?.publish('gd.local.approval.cancelled', { transactionId, jobId: current.jobId, occurredAt: now }); return changed; }
  async consume(transactionId: ApprovalTransactionId, receipt: string, expectedPayloadDigest: string): Promise<ApprovalTransactionRecord> { this.#assertReady(); if (!validReceipt(receipt)) throw new Error('Approval receipt is missing or invalid.'); const digest = normalizeDigest(expectedPayloadDigest); const current = this.get(transactionId); if (!current) throw new Error(`Unknown approval transaction ${transactionId}.`); if (current.state !== 'approved') throw new Error(`Approval transaction is ${current.state}, not approved.`); if (current.payloadDigest !== digest) throw new Error('Approval payload digest mismatch.'); this.#assertJobActive(current.jobId); const now = this.#now(); if (Date.parse(current.expiresAt) <= Date.parse(now)) { await this.#expireOne(transactionId, now); throw new Error('Approval transaction expired before consumption.'); } const hash = receiptHash(receipt); const changed = this.#database.transaction((database) => Number(database.prepare("UPDATE gd_approval_transactions SET state = 'consumed', consumed_at = ?, receipt_hash = NULL WHERE id = ? AND state = 'approved' AND receipt_hash = ?").run(now, transactionId, hash).changes) === 1); if (!changed) throw new Error('Approval receipt is invalid, already consumed or changed concurrently.'); const transaction = this.get(transactionId)!; await this.#eventBus?.publish('gd.local.approval.consumed', { transactionId, jobId: current.jobId, occurredAt: now }); return transaction; }
  get(transactionId: ApprovalTransactionId): ApprovalTransactionRecord | null { if (!this.#database.isOpen) return null; const row = this.#database.read((database) => database.prepare('SELECT id, job_id, action, summary, requirements_json, payload_digest, state, requested_at, expires_at, decided_at, decided_by, decision_reason, consumed_at FROM gd_approval_transactions WHERE id = ?').get(transactionId) as ApprovalRow | undefined); return row ? this.#record(row) : null; }
  async expirePending(): Promise<number> { if (!this.#database.isOpen || (this.#database.status?.schemaVersion ?? 0) < 7) return 0; const now = this.#now(); return this.#database.transaction((database) => Number(database.prepare("UPDATE gd_approval_transactions SET state = 'expired', decided_at = COALESCE(decided_at, ?), decision_reason = COALESCE(decision_reason, 'expired'), receipt_hash = NULL WHERE state IN ('pending', 'approved') AND expires_at <= ?").run(now, now).changes)); }
  shutdown(): void { this.#ready = false; }
  #requirePending(id: ApprovalTransactionId): ApprovalTransactionRecord { const current = this.get(id); if (!current) throw new Error(`Unknown approval transaction ${id}.`); if (current.state !== 'pending') throw new Error(`Approval transaction is ${current.state}, not pending.`); return current; }
  async #expireOne(id: ApprovalTransactionId, now: string): Promise<void> { this.#database.transaction((database) => database.prepare("UPDATE gd_approval_transactions SET state = 'expired', decided_at = COALESCE(decided_at, ?), decision_reason = COALESCE(decision_reason, 'expired'), receipt_hash = NULL WHERE id = ? AND state IN ('pending','approved')").run(now, id)); }
  #assertJobActive(jobId: DurableJobId): void { const row = this.#database.read((database) => database.prepare('SELECT state FROM gd_jobs WHERE id = ?').get(jobId) as JobStateRow | undefined); if (!row) throw new Error(`Unknown durable job ${jobId}.`); const state = text(row.state, 'durable job state') as DurableJobState; if (isDurableJobTerminalState(state)) throw new Error(`Approval transaction cannot be used by terminal job ${jobId} (${state}).`); }
  #record(row: ApprovalRow): ApprovalTransactionRecord { const requirements = JSON.parse(text(row.requirements_json, 'approval requirements')) as ApprovalRequirement[]; return Object.freeze({ id: text(row.id, 'approval id') as ApprovalTransactionId, jobId: text(row.job_id, 'approval job id') as DurableJobId, action: text(row.action, 'approval action'), summary: text(row.summary, 'approval summary'), requirements: normalizeRequirements(requirements), payloadDigest: normalizeDigest(text(row.payload_digest, 'approval payload digest')), state: text(row.state, 'approval state') as ApprovalState, requestedAt: text(row.requested_at, 'approval requested_at'), expiresAt: text(row.expires_at, 'approval expires_at'), decidedAt: nullableText(row.decided_at, 'approval decided_at'), decidedBy: nullableText(row.decided_by, 'approval decided_by'), decisionReason: nullableText(row.decision_reason, 'approval decision_reason'), consumedAt: nullableText(row.consumed_at, 'approval consumed_at') }); }
  #assertReady(): void { if (!this.#ready) throw new Error('Approval Transactions authority is not ready.'); }
}
export function createApprovalTransactions(options: ApprovalTransactionsOptions): ApprovalTransactions { return new ApprovalTransactions(options); }
