import type { AiChangeSessionId, GitOperation } from '@github-decrypter/git';
import type { GitHubInstallationState } from '@github-decrypter/github-app';
import type { GitHubProviderOperation } from '@github-decrypter/github-provider';
import type { ProjectDetectionConfidence, ProjectFramework, ProjectPackageManager, WorkspaceId } from '@github-decrypter/workspace';
import type { LocalAIRuntimeOperation } from './ai-runtime.js';
import type { ApprovalTransactionId } from './approval-transactions.js';
import type { AuditCategory, AuditEntryId, AuditOutcome } from './audit-ledger.js';
import type { Capability, CapabilityGrantId } from './capability-security.js';
import type { DurableJobId, DurableJobState } from './job-types.js';
import type { ConnectivityState } from './offline-execution.js';

export const LOCAL_RUNTIME_STATES = ['idle','starting','running','stopping','stopped','failed'] as const;
export type LocalRuntimeState = (typeof LOCAL_RUNTIME_STATES)[number];

export type LocalRuntimeLifecyclePayload = { readonly previous: LocalRuntimeState; readonly current: LocalRuntimeState; readonly reason: string | null; };
export type LocalRuntimeDatabaseOpenedPayload = { readonly schemaVersion: number; readonly journalMode: string; readonly foreignKeys: boolean; readonly integrity: 'ok'; };
export type LocalRuntimeDatabaseClosedPayload = { readonly schemaVersion: number; readonly reason: string | null; };
export type LocalRuntimeJobsReadyPayload = { readonly schemaVersion: number; readonly total: number; readonly nonTerminal: number; readonly expiredLeases: number; };
export type LocalRuntimeJobChangedPayload = { readonly jobId: DurableJobId; readonly previousState: DurableJobState | null; readonly currentState: DurableJobState; readonly reason: string | null; };
export type LocalRuntimeRecoveryReadyPayload = { readonly priorUncleanSessions: number; readonly startupRecovered: number; };
export type LocalRuntimeRecoverySweepPayload = { readonly recovered: number; readonly requeued: number; readonly paused: number; readonly cancelled: number; readonly failed: number; readonly occurredAt: string; };
export type LocalRuntimeRecoveryClosedPayload = { readonly handoffRecovered: number; readonly clean: boolean; readonly reason: string; };
export type LocalRuntimeOfflineReadyPayload = { readonly connectivity: ConnectivityState; readonly waitingForNetwork: number; readonly localExecutionAvailable: true; readonly automaticNetworkProbe: false; };
export type LocalRuntimeConnectivityChangedPayload = { readonly previous: ConnectivityState; readonly current: ConnectivityState; readonly source: string; readonly observedAt: string; readonly waitingForNetwork: number; };
export type LocalRuntimeOfflineWaitingPayload = { readonly jobId: DurableJobId; readonly reason: string; readonly blockedAt: string; };
export type LocalRuntimeOfflineResumedPayload = { readonly jobId: DurableJobId; readonly resumedAt: string; };
export type LocalRuntimeCapabilityReadyPayload = { readonly activeGrants: number; readonly restartRevocations: number; readonly denyByDefault: true; readonly plaintextTokenPersistence: false; readonly secretsVaultReady: false; readonly approvalTransactionsReady: false; readonly externalGrantTransport: false; };
export type LocalRuntimeCapabilityGrantedPayload = { readonly grantId: CapabilityGrantId; readonly jobId: DurableJobId; readonly capabilities: Capability[]; readonly claimCount: number; readonly issuedAt: string; readonly expiresAt: string; };
export type LocalRuntimeCapabilityRevokedPayload = { readonly grantId: CapabilityGrantId; readonly jobId: DurableJobId; readonly reason: string; readonly revokedAt: string; };
export type LocalRuntimeCapabilityDeniedPayload = { readonly grantId: CapabilityGrantId | null; readonly jobId: DurableJobId; readonly reason: string; readonly missingCapabilities: Capability[]; readonly missingCount: number; };
export type LocalRuntimeVaultReadyPayload = { readonly secretCount: number; readonly cipher: 'AES-256-GCM'; readonly keyBackend: 'local-key-file-v1'; readonly plaintextPersistence: false; readonly externalTransport: false; };
export type LocalRuntimeVaultSecretChangedPayload = { readonly secretId: string; readonly operation: 'created' | 'updated' | 'deleted'; readonly occurredAt: string; };
export type LocalRuntimeApprovalReadyPayload = { readonly pending: number; readonly approved: number; readonly oneShotReceipts: true; readonly plaintextReceiptPersistence: false; readonly externalDecisionTransport: false; };
export type LocalRuntimeApprovalRequestedPayload = { readonly transactionId: ApprovalTransactionId; readonly jobId: DurableJobId; readonly action: string; readonly expiresAt: string; };
export type LocalRuntimeApprovalDecidedPayload = { readonly transactionId: ApprovalTransactionId; readonly jobId: DurableJobId; readonly decision: 'approved' | 'denied'; readonly actor: string; readonly occurredAt: string; };
export type LocalRuntimeApprovalConsumedPayload = { readonly transactionId: ApprovalTransactionId; readonly jobId: DurableJobId; readonly occurredAt: string; };
export type LocalRuntimeApprovalCancelledPayload = { readonly transactionId: ApprovalTransactionId; readonly jobId: DurableJobId; readonly occurredAt: string; };
export type LocalRuntimeAuditReadyPayload = { readonly entryCount: number; readonly headHash: string; readonly appendOnly: true; readonly hashChain: 'sha256'; readonly externalTransport: false; };
export type LocalRuntimeAuditAppendedPayload = { readonly entryId: AuditEntryId; readonly sequence: number; readonly category: AuditCategory; readonly action: string; readonly outcome: AuditOutcome; readonly occurredAt: string; };
export type LocalRuntimeWorkspaceReadyPayload = { readonly registered: number; readonly available: number; readonly filesystemMutation: false; readonly externalTransport: false; };
export type LocalRuntimeWorkspaceRegisteredPayload = { readonly workspaceId: WorkspaceId; readonly registeredAt: string; };
export type LocalRuntimeWorkspaceOpenedPayload = { readonly workspaceId: WorkspaceId; readonly openedAt: string; };
export type LocalRuntimeWorkspaceUnregisteredPayload = { readonly workspaceId: WorkspaceId; readonly occurredAt: string; };
export type LocalRuntimeProjectDetectionReadyPayload = { readonly detections: number; readonly rootOnly: true; readonly readOnly: true; readonly filesystemMutation: false; readonly networkAccess: false; readonly gitAuthority: false; readonly externalTransport: false; };
export type LocalRuntimeProjectDetectedPayload = { readonly workspaceId: WorkspaceId; readonly packageJsonPresent: boolean; readonly packageManager: ProjectPackageManager; readonly framework: ProjectFramework; readonly confidence: ProjectDetectionConfidence; readonly detectedAt: string; };
export type LocalRuntimeGitReadyPayload = { readonly available: boolean; readonly version: string | null; readonly shellExecution: false; readonly forcePush: false; readonly hardReset: false; readonly externalTransport: false; };
export type LocalRuntimeGitOperationPayload = { readonly workspaceId: WorkspaceId; readonly operation: GitOperation; readonly mutating: boolean; readonly network: boolean; readonly outcome: 'success' | 'failure'; readonly exitCode: number | null; readonly occurredAt: string; };
export type LocalRuntimeChangeTrackingReadyPayload = { readonly activeSessions: number; readonly trackedPaths: number; readonly explicitBoundaries: true; readonly contentPersistence: false; readonly filesystemMutation: false; readonly externalTransport: false; };
export type LocalRuntimeHumanChangesObservedPayload = { readonly workspaceId: WorkspaceId; readonly changedPaths: number; readonly human: number; readonly mixed: number; readonly unknown: number; readonly observedAt: string; };
export type LocalRuntimeAiChangeStartedPayload = { readonly sessionId: AiChangeSessionId; readonly workspaceId: WorkspaceId; readonly jobId: DurableJobId; readonly baselinePaths: number; readonly startedAt: string; };
export type LocalRuntimeAiChangeCompletedPayload = { readonly sessionId: AiChangeSessionId; readonly workspaceId: WorkspaceId; readonly jobId: DurableJobId; readonly changedPaths: number; readonly ai: number; readonly mixed: number; readonly unknown: number; readonly completedAt: string; };
export type LocalRuntimeChangeTrackingInvalidatedPayload = { readonly sessionId: AiChangeSessionId; readonly workspaceId: WorkspaceId; readonly jobId: DurableJobId; readonly reason: string; readonly occurredAt: string; };
export type LocalRuntimeGitHubAppReadyPayload = { readonly configured: boolean; readonly installationCount: number; readonly installationTokenPersistence: false; readonly webhookPayloadPersistence: false; readonly genericHttpTransport: false; };
export type LocalRuntimeGitHubAppConfiguredPayload = { readonly appId: string; readonly configuredAt: string; readonly updatedAt: string; };
export type LocalRuntimeGitHubAppInstallationChangedPayload = { readonly installationId: number; readonly state: GitHubInstallationState; readonly updatedAt: string; };
export type LocalRuntimeGitHubAppInstallationTokenCreatedPayload = { readonly installationId: number; readonly expiresAt: string; readonly persisted: false; };
export type LocalRuntimeGitHubAppWebhookVerifiedPayload = { readonly deliveryId: string; readonly event: string; readonly valid: boolean; readonly duplicate: boolean; readonly verifiedAt: string; readonly payloadPersistence: false; };
export type LocalRuntimeGitHubProviderReadyPayload = { readonly configured: boolean; readonly operations: GitHubProviderOperation[]; readonly readOnly: true; readonly installationTokenPersistence: false; readonly responsePersistence: false; readonly genericRequestApi: false; };
export type LocalRuntimeGitHubProviderOperationPayload = { readonly operation: GitHubProviderOperation; readonly installationId: number; readonly outcome: 'success' | 'failure'; readonly itemCount: number; readonly occurredAt: string; };
export type LocalRuntimeAIRuntimeReadyPayload = { readonly registeredProviders: number; readonly localOnly: true; readonly runtimeExecution: true; readonly networkAuthority: false; readonly secretsAuthority: false; readonly persistence: false; readonly automaticRouting: false; };
export type LocalRuntimeAIRuntimeOperationPayload = { readonly operation: LocalAIRuntimeOperation; readonly providerId: string | null; readonly modelId: string | null; readonly outcome: 'success' | 'failure'; readonly itemCount: number; readonly occurredAt: string; readonly promptPersistence: false; readonly responsePersistence: false; };

export type LocalRuntimeEventCatalog = {
  readonly 'gd.local.lifecycle': LocalRuntimeLifecyclePayload;
  readonly 'gd.local.database.opened': LocalRuntimeDatabaseOpenedPayload;
  readonly 'gd.local.database.closed': LocalRuntimeDatabaseClosedPayload;
  readonly 'gd.local.jobs.ready': LocalRuntimeJobsReadyPayload;
  readonly 'gd.local.job.changed': LocalRuntimeJobChangedPayload;
  readonly 'gd.local.recovery.ready': LocalRuntimeRecoveryReadyPayload;
  readonly 'gd.local.recovery.sweep': LocalRuntimeRecoverySweepPayload;
  readonly 'gd.local.recovery.closed': LocalRuntimeRecoveryClosedPayload;
  readonly 'gd.local.offline.ready': LocalRuntimeOfflineReadyPayload;
  readonly 'gd.local.connectivity.changed': LocalRuntimeConnectivityChangedPayload;
  readonly 'gd.local.offline.waiting': LocalRuntimeOfflineWaitingPayload;
  readonly 'gd.local.offline.resumed': LocalRuntimeOfflineResumedPayload;
  readonly 'gd.local.capability.ready': LocalRuntimeCapabilityReadyPayload;
  readonly 'gd.local.capability.granted': LocalRuntimeCapabilityGrantedPayload;
  readonly 'gd.local.capability.revoked': LocalRuntimeCapabilityRevokedPayload;
  readonly 'gd.local.capability.denied': LocalRuntimeCapabilityDeniedPayload;
  readonly 'gd.local.vault.ready': LocalRuntimeVaultReadyPayload;
  readonly 'gd.local.vault.secret.changed': LocalRuntimeVaultSecretChangedPayload;
  readonly 'gd.local.approval.ready': LocalRuntimeApprovalReadyPayload;
  readonly 'gd.local.approval.requested': LocalRuntimeApprovalRequestedPayload;
  readonly 'gd.local.approval.decided': LocalRuntimeApprovalDecidedPayload;
  readonly 'gd.local.approval.consumed': LocalRuntimeApprovalConsumedPayload;
  readonly 'gd.local.approval.cancelled': LocalRuntimeApprovalCancelledPayload;
  readonly 'gd.local.audit.ready': LocalRuntimeAuditReadyPayload;
  readonly 'gd.local.audit.appended': LocalRuntimeAuditAppendedPayload;
  readonly 'gd.local.workspace.ready': LocalRuntimeWorkspaceReadyPayload;
  readonly 'gd.local.workspace.registered': LocalRuntimeWorkspaceRegisteredPayload;
  readonly 'gd.local.workspace.opened': LocalRuntimeWorkspaceOpenedPayload;
  readonly 'gd.local.workspace.unregistered': LocalRuntimeWorkspaceUnregisteredPayload;
  readonly 'gd.local.project-detection.ready': LocalRuntimeProjectDetectionReadyPayload;
  readonly 'gd.local.project.detected': LocalRuntimeProjectDetectedPayload;
  readonly 'gd.local.git.ready': LocalRuntimeGitReadyPayload;
  readonly 'gd.local.git.operation': LocalRuntimeGitOperationPayload;
  readonly 'gd.local.change-tracking.ready': LocalRuntimeChangeTrackingReadyPayload;
  readonly 'gd.local.change-tracking.human-observed': LocalRuntimeHumanChangesObservedPayload;
  readonly 'gd.local.change-tracking.ai-started': LocalRuntimeAiChangeStartedPayload;
  readonly 'gd.local.change-tracking.ai-completed': LocalRuntimeAiChangeCompletedPayload;
  readonly 'gd.local.change-tracking.invalidated': LocalRuntimeChangeTrackingInvalidatedPayload;
  readonly 'gd.local.github-app.ready': LocalRuntimeGitHubAppReadyPayload;
  readonly 'gd.local.github-app.configured': LocalRuntimeGitHubAppConfiguredPayload;
  readonly 'gd.local.github-app.installation.changed': LocalRuntimeGitHubAppInstallationChangedPayload;
  readonly 'gd.local.github-app.installation-token.created': LocalRuntimeGitHubAppInstallationTokenCreatedPayload;
  readonly 'gd.local.github-app.webhook.verified': LocalRuntimeGitHubAppWebhookVerifiedPayload;
  readonly 'gd.local.github-provider.ready': LocalRuntimeGitHubProviderReadyPayload;
  readonly 'gd.local.github-provider.operation': LocalRuntimeGitHubProviderOperationPayload;
  readonly 'gd.local.ai-runtime.ready': LocalRuntimeAIRuntimeReadyPayload;
  readonly 'gd.local.ai-runtime.operation': LocalRuntimeAIRuntimeOperationPayload;
};

export function isLocalRuntimeState(value: unknown): value is LocalRuntimeState {
  return typeof value === 'string' && LOCAL_RUNTIME_STATES.includes(value as LocalRuntimeState);
}
