import { createClient } from "jsr:@supabase/supabase-js@2.112.4";
import postgres from "npm:postgres@3.4.9";
import { zipSync, strToU8 } from "npm:fflate@0.8.2";

const PUBLIC_SPKI_B64 = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE/suDKmZG7B52xCVkCooS5MZfvVu+GjYTIfeOvlfi9tz29TQNN4uea318Nn2xf5uf/cm0bpaCADPwkqWSZV2MIA==";
const API_BASE = "https://api.supabase.com/v1";
const REQUIRED_SCOPES = ["projects:read","database:read","database:write","auth:read","auth:write","edge_functions:read","edge_functions:write","secrets:read","secrets:write","storage:read"];
const OBJECT_BATCH = 4, MAX_LOGS = 120;
const BUILTIN_SECRETS = new Set(["SUPABASE_URL","SUPABASE_ANON_KEY","SUPABASE_PUBLISHABLE_KEY","SUPABASE_SERVICE_ROLE_KEY","SUPABASE_SECRET_KEY","SUPABASE_DB_URL","DATABASE_URL","DENO_DEPLOYMENT_ID","SB_EXECUTION_ID","SB_REGION","SB_RUNTIME_VERSION"]);
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"content-type,x-license-key,x-device-id,authorization","Access-Control-Allow-Methods":"POST,OPTIONS"};
const enc=new TextEncoder(),dec=new TextDecoder();
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json","Cache-Control":"no-store"}});
function b64url(bytes:Uint8Array){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function unb64url(v:string){const s=v.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(v.length/4)*4,"=");return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function randomValue(size=48){return b64url(crypto.getRandomValues(new Uint8Array(size)))}
async function shaHex(v:string){const d=await crypto.subtle.digest("SHA-256",enc.encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
function serviceKey(){const current=Deno.env.get("SUPABASE_SECRET_KEYS");if(current){try{const p=JSON.parse(current);if(p?.default)return String(p.default);const first=Object.values(p||{})[0];if(first)return String(first)}catch(_){}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||""}
function admin(){const url=Deno.env.get("SUPABASE_URL")||"",key=serviceKey();if(!url||!key)throw new Error("BACKEND_NOT_CONFIGURED");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function publicKey(){const der=Uint8Array.from(atob(PUBLIC_SPKI_B64),c=>c.charCodeAt(0));return crypto.subtle.importKey("spki",der,{name:"ECDSA",namedCurve:"P-256"},false,["verify"])}
async function verifyLicenseToken(token:string){const [prefix,payloadPart,sigPart]=token.trim().split(".");if(prefix!=="LD2"||!payloadPart||!sigPart)throw new Error("KEY_INVALID_FORMAT");const ok=await crypto.subtle.verify({name:"ECDSA",hash:"SHA-256"},await publicKey(),unb64url(sigPart),enc.encode(payloadPart));if(!ok)throw new Error("KEY_INVALID_SIGNATURE");const payload=JSON.parse(dec.decode(unb64url(payloadPart)));if(payload?.aud!=="lovable-decrypter"||Number(payload?.v)!==1||!payload?.license_id)throw new Error("KEY_INVALID_PAYLOAD");return payload}
async function authorize(req:Request,sb:any){const bearer=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim(),token=String(req.headers.get("x-license-key")||bearer||"").trim(),deviceId=String(req.headers.get("x-device-id")||"").trim();if(!token)throw new Error("KEY_REQUIRED");if(!deviceId)throw new Error("DEVICE_REQUIRED");const signed=await verifyLicenseToken(token);const {data:license,error}=await sb.from("ld_license_keys").select("id,status,expires_at,credit_balance,credit_debt").eq("id",String(signed.license_id)).eq("key_hash",await shaHex(token)).maybeSingle();if(error)throw new Error("DB_ERROR");if(!license)throw new Error("KEY_NOT_REGISTERED");if(license.status!=="active")throw new Error(`KEY_${String(license.status).toUpperCase()}`);const timeActive=Boolean(license.expires_at&&Date.parse(license.expires_at)>Date.now()),creditActive=!timeActive&&Number(license.credit_debt||0)===0&&Number(license.credit_balance||0)>0;if(!timeActive&&!creditActive)throw new Error("ENTITLEMENT_EXHAUSTED");const deviceHash=await shaHex(deviceId);const {data:device,error:de}=await sb.from("ld_license_devices").select("id,revoked_at").eq("license_id",license.id).eq("device_hash",deviceHash).maybeSingle();if(de)throw new Error("DB_ERROR");if(!device)throw new Error("DEVICE_NOT_BOUND");if(device.revoked_at)throw new Error("DEVICE_REVOKED");return{licenseId:String(license.id),deviceHash}}
async function getSecret(sb:any,name:string){const {data,error}=await sb.rpc("ld_backend_secret",{p_name:name});if(error||!data)throw new Error(`SECRET_MISSING:${name}`);return String(data)}
async function storeSecret(sb:any,name:string,value:string,description:string){const {error}=await sb.rpc("ld_backend_secret_set",{p_name:name,p_value:value,p_description:description});if(error)throw new Error(`SECRET_STORE_FAILED:${name}`)}
async function deleteSecret(sb:any,name:string){const {error}=await sb.rpc("ld_backend_secret_delete",{p_name:name});if(error)throw new Error(`SECRET_DELETE_FAILED:${name}`)}
async function oauthConfig(sb:any){const {data,error}=await sb.from("ld_supabase_oauth_config").select("*").eq("singleton",true).maybeSingle();if(error||!data)throw new Error("SUPABASE_OAUTH_APP_NOT_CONFIGURED");return data}
async function oauthConnection(sb:any,licenseId:string,deviceHash:string){const {data,error}=await sb.from("ld_supabase_connections").select("*").eq("license_id",licenseId).eq("device_hash",deviceHash).maybeSingle();if(error)throw new Error("CONNECTION_READ_FAILED");if(!data)throw new Error("SUPABASE_NOT_CONNECTED");return data}
function basicAuth(id:string,secret:string){return `Basic ${btoa(`${id}:${secret}`)}`}
function missingScopes(scope:string){const granted=new Set(String(scope||"").split(/[\s,]+/).filter(Boolean));return REQUIRED_SCOPES.filter(x=>!granted.has(x))}
async function accessToken(sb:any,licenseId:string,deviceHash:string){const config=await oauthConfig(sb),connection=await oauthConnection(sb,licenseId,deviceHash),refresh=await getSecret(sb,String(connection.refresh_secret_name)),secret=await getSecret(sb,"LD_SUPABASE_OAUTH_CLIENT_SECRET"),body=new URLSearchParams({grant_type:"refresh_token",refresh_token:refresh});const res=await fetch(`${API_BASE}/oauth/token`,{method:"POST",headers:{Authorization:basicAuth(String(config.client_id),secret),"Content-Type":"application/x-www-form-urlencoded",Accept:"application/json"},body});const data=await res.json().catch(()=>null);if(!res.ok||!data?.access_token)throw new Error(`TOKEN_REFRESH_FAILED:${res.status}`);if(data.refresh_token&&String(data.refresh_token)!==refresh)await storeSecret(sb,String(connection.refresh_secret_name),String(data.refresh_token),"Lovable Decrypter Supabase OAuth refresh token");const scope=String(data.scope||connection.granted_scope||"");return{token:String(data.access_token),scope,missing:missingScopes(scope)}}
async function management(token:string,path:string,options:RequestInit={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),55000);try{const res=await fetch(`${API_BASE}${path}`,{...options,signal:controller.signal,headers:{Authorization:`Bearer ${token}`,Accept:"application/json",...(options.headers||{})}}),ct=res.headers.get("content-type")||"",data=ct.includes("json")?await res.json().catch(()=>null):await res.text().catch(()=>"");if(!res.ok)throw new Error(`SUPABASE_MANAGEMENT_HTTP_${res.status}:${(data as any)?.message||(data as any)?.error||"request failed"}`);return data}finally{clearTimeout(timer)}}
async function destQuery(token:string,ref:string,query:string){return management(token,`/projects/${encodeURIComponent(ref)}/database/query`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query})})}
function names(id:string){const k=id.replace(/-/g,"").toUpperCase();return{db:`LD_CLOUD_ASSET_DB_${k}`,url:`LD_CLOUD_ASSET_URL_${k}`,api:`LD_CLOUD_ASSET_KEY_${k}`}}
function terminal(status:string){return["completed","cancelled","failed"].includes(status)}
function sanitize(job:any){if(!job)return null;const {device_hash,handoff_token_hash,source_db_secret_name,source_url_secret_name,source_key_secret_name,...safe}=job;return safe}
function appendLog(job:any,level:string,message:string){const logs=Array.isArray(job?.logs)?[...job.logs]:[];logs.push({at:new Date().toISOString(),level,message:String(message).slice(0,900)});return logs.slice(-MAX_LOGS)}
async function updateJob(sb:any,job:any,patch:any,log?:{level:string,message:string}){const next={...patch,updated_at:new Date().toISOString()};if(log)next.logs=appendLog(job,log.level,log.message);const {data,error}=await sb.from("ld_cloud_asset_jobs").update(next).eq("id",job.id).select("*").single();if(error)throw new Error("ASSET_JOB_UPDATE_FAILED");return data}
async function ownedJob(sb:any,id:string,auth:any){const {data,error}=await sb.from("ld_cloud_asset_jobs").select("*").eq("id",id).eq("license_id",auth.licenseId).eq("device_hash",auth.deviceHash).maybeSingle();if(error)throw new Error("ASSET_JOB_READ_FAILED");if(!data)throw new Error("ASSET_JOB_NOT_FOUND");return data}
async function cleanup(sb:any,job:any){for(const name of[job.source_db_secret_name,job.source_url_secret_name,job.source_key_secret_name].filter(Boolean)){try{await deleteSecret(sb,String(name))}catch(_){}}}
async function withSourceDb<T>(sb:any,job:any,fn:(sql:any)=>Promise<T>){const url=await getSecret(sb,String(job.source_db_secret_name)),sql=postgres(url,{prepare:false,max:1,connect_timeout:12,idle_timeout:5});try{return await fn(sql)}finally{await sql.end({timeout:2}).catch(()=>{})}}
async function sourceClient(sb:any,job:any){const url=await getSecret(sb,String(job.source_url_secret_name)),key=await getSecret(sb,String(job.source_key_secret_name));return{url,key,client:createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}}
async function destinationClient(token:string,ref:string){const keys=await management(token,`/projects/${encodeURIComponent(ref)}/api-keys?reveal=true`),list=Array.isArray(keys)?keys:[],elevated=list.find((x:any)=>String(x?.name||"").toLowerCase().includes("service_role"))||list.find((x:any)=>String(x?.type||"").toLowerCase()==="secret")||list.find((x:any)=>String(x?.api_key||"").startsWith("sb_secret_")),key=String(elevated?.api_key||elevated?.key||"");if(!key)throw new Error("DESTINATION_SERVER_KEY_UNAVAILABLE");const url=`https://${ref}.supabase.co`;return{url,key,client:createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}}
function qid(v:string){return `"${String(v).replace(/"/g,'""')}"`}function qlit(v:string){return `'${String(v).replace(/'/g,"''")}'`}
async function inspect(sb:any,job:any){return withSourceDb(sb,job,async sql=>{const buckets=await sql.unsafe(`select id,name,public,file_size_limit,allowed_mime_types from storage.buckets order by id`),counts=await sql.unsafe(`select bucket_id,count(*)::bigint as objects,coalesce(sum(nullif(metadata->>'size','')::bigint),0)::bigint as bytes from storage.objects group by bucket_id order by bucket_id`),policies=await sql.unsafe(`select schemaname,tablename,policyname,permissive,roles,cmd,qual,with_check from pg_catalog.pg_policies where schemaname='storage' and tablename in ('objects','buckets') order by tablename,policyname`),realtime=await sql.unsafe(`select schemaname,tablename from pg_catalog.pg_publication_tables where pubname='supabase_realtime' and schemaname='public' order by tablename`),totalObjects=counts.reduce((n:number,x:any)=>n+Number(x.objects||0),0),totalBytes=counts.reduce((n:number,x:any)=>n+Number(x.bytes||0),0);return{buckets,counts,storagePolicies:policies,realtime,totalObjects,totalBytes}})}
function safeRoles(value:any){const roles=Array.isArray(value)?value:String(value||"").replace(/[{}]/g,"").split(",");return roles.map((x:any)=>String(x).trim().replace(/^"|"$/g,"")).filter(x=>/^[A-Za-z_][A-Za-z0-9_]*$/.test(x))}
async function applyStoragePolicy(token:string,ref:string,p:any){if(!["objects","buckets"].includes(String(p.tablename)))return;const roles=safeRoles(p.roles);if(!roles.length)return;const cmd=String(p.cmd||"ALL").toUpperCase();if(!["ALL","SELECT","INSERT","UPDATE","DELETE"].includes(cmd))throw new Error("STORAGE_POLICY_COMMAND_INVALID");const name=String(p.policyname||"");if(!name)return;const permissive=String(p.permissive||"PERMISSIVE").toUpperCase()==="RESTRICTIVE"?"RESTRICTIVE":"PERMISSIVE",using=p.qual?` using (${p.qual})`:"",check=p.with_check?` with check (${p.with_check})`:"";await destQuery(token,ref,`drop policy if exists ${qid(name)} on storage.${qid(p.tablename)}; create policy ${qid(name)} on storage.${qid(p.tablename)} as ${permissive} for ${cmd} to ${roles.map(qid).join(",")}${using}${check};`)}
function objectPath(path:string){return String(path).split("/").map(encodeURIComponent).join("/")}
async function streamObject(source:any,dest:any,bucket:string,path:string,metadata:any){const read=await fetch(`${source.url.replace(/\/+$/,"")}/storage/v1/object/authenticated/${encodeURIComponent(bucket)}/${objectPath(path)}`,{headers:{apikey:source.key,Authorization:`Bearer ${source.key}`}});if(!read.ok||!read.body)throw new Error(`SOURCE_OBJECT_HTTP_${read.status}:${bucket}/${path}`);const headers:any={apikey:dest.key,Authorization:`Bearer ${dest.key}`,"x-upsert":"true","Content-Type":String(metadata?.mimetype||metadata?.contentType||read.headers.get("content-type")||"application/octet-stream")};const cache=metadata?.cacheControl||metadata?.cache_control;if(cache)headers["cache-control"]=String(cache);const write=await fetch(`${dest.url.replace(/\/+$/,"")}/storage/v1/object/${encodeURIComponent(bucket)}/${objectPath(path)}`,{method:"POST",headers,body:read.body});if(!write.ok){const msg=await write.text().catch(()=>"");throw new Error(`DEST_OBJECT_HTTP_${write.status}:${bucket}/${path}:${msg.slice(0,120)}`)}}
async function nextObjects(sb:any,job:any,offset:number){return withSourceDb(sb,job,async sql=>sql.unsafe(`select bucket_id,name,metadata from storage.objects order by bucket_id,name limit ${OBJECT_BATCH} offset ${Math.max(0,offset|0)}`))}
async function deployFunction(token:string,ref:string,slug:string,files:any[],verifyJwt:boolean){if(!/^[a-z0-9][a-z0-9_-]{0,63}$/i.test(slug))throw new Error("FUNCTION_SLUG_INVALID");if(!Array.isArray(files)||!files.length)throw new Error("FUNCTION_FILES_REQUIRED");const zipped:Record<string,Uint8Array>={};let total=0;for(const file of files){const path=String(file?.path||""),content=String(file?.content??"");if(!/^supabase\/functions\/[A-Za-z0-9_-]+\//.test(path))throw new Error("FUNCTION_PATH_INVALID");total+=content.length;if(total>8*1024*1024)throw new Error("FUNCTION_BUNDLE_TOO_LARGE");zipped[path]=strToU8(content)}const zip=zipSync(zipped,{level:6}),form=new FormData();form.append("file",new Blob([zip],{type:"application/zip"}),`${slug}.zip`);form.append("metadata",JSON.stringify({slug,name:slug,verify_jwt:!!verifyJwt,entrypoint_path:`supabase/functions/${slug}/index.ts`}));return management(token,`/projects/${encodeURIComponent(ref)}/functions/deploy?slug=${encodeURIComponent(slug)}`,{method:"POST",body:form})}
function safeConfig(input:any){const auth:any={};if(input?.auth&&typeof input.auth==="object"){if(typeof input.auth.site_url==="string"&&/^https?:\/\//i.test(input.auth.site_url))auth.site_url=input.auth.site_url.slice(0,2048);if(typeof input.auth.uri_allow_list==="string")auth.uri_allow_list=input.auth.uri_allow_list.slice(0,8192);if(typeof input.auth.disable_signup==="boolean")auth.disable_signup=input.auth.disable_signup}return{auth}}
async function runNext(sb:any,job:any,auth:any){if(terminal(job.status))return job;const session=await accessToken(sb,auth.licenseId,auth.deviceHash);if(session.missing.length)throw Object.assign(new Error("SUPABASE_REAUTH_REQUIRED"),{missingScopes:session.missing});const ref=String(job.destination_project_ref),progress={...(job.progress||{})},inventory={...(job.inventory||{})},phase=String(job.phase||"storage_buckets");
if(phase==="storage_buckets"){const buckets=Array.isArray(inventory.buckets)?inventory.buckets:[],i=Number(progress.bucket_index||0);if(i>=buckets.length)return updateJob(sb,job,{phase:"storage_objects",status:"running",progress:{...progress,object_offset:0,objects_done:0}},{level:"info",message:"Buckets concluídos."});const dest=await destinationClient(session.token,ref),bucket=buckets[i],opts:any={public:!!bucket.public};if(bucket.file_size_limit!=null)opts.fileSizeLimit=Number(bucket.file_size_limit);if(Array.isArray(bucket.allowed_mime_types))opts.allowedMimeTypes=bucket.allowed_mime_types;const {data:existing}=await dest.client.storage.getBucket(String(bucket.id)),result=existing?await dest.client.storage.updateBucket(String(bucket.id),opts):await dest.client.storage.createBucket(String(bucket.id),opts);if(result.error)throw new Error(`BUCKET_${bucket.id}:${result.error.message}`);return updateJob(sb,job,{status:"running",progress:{...progress,bucket_index:i+1,current:`bucket ${bucket.id}`}},{level:"info",message:`Bucket ${bucket.id} pronto.`})}
if(phase==="storage_objects"){const offset=Number(progress.object_offset||0),rows=await nextObjects(sb,job,offset);if(!rows.length)return updateJob(sb,job,{phase:"storage_policies",progress:{...progress,policy_index:0}},{level:"info",message:"Objetos do Storage concluídos."});const source=await sourceClient(sb,job),dest=await destinationClient(session.token,ref);let done=Number(progress.objects_done||0);for(const row of rows){await streamObject(source,dest,String(row.bucket_id),String(row.name),row.metadata||{});done++}return updateJob(sb,job,{status:"running",progress:{...progress,object_offset:offset+rows.length,objects_done:done,current:`Storage ${done}/${Number(inventory.totalObjects||0)}`}},{level:"info",message:`${rows.length} objeto(s) copiados.`})}
if(phase==="storage_policies"){const policies=Array.isArray(inventory.storagePolicies)?inventory.storagePolicies:[],i=Number(progress.policy_index||0);if(i>=policies.length)return updateJob(sb,job,{phase:"realtime",progress:{...progress,realtime_index:0}},{level:"info",message:"Policies do Storage concluídas."});await applyStoragePolicy(session.token,ref,policies[i]);return updateJob(sb,job,{progress:{...progress,policy_index:i+1,current:`policy ${policies[i].policyname}`}})}
if(phase==="realtime"){const tables=Array.isArray(inventory.realtime)?inventory.realtime:[],i=Number(progress.realtime_index||0);if(i>=tables.length)return updateJob(sb,job,{phase:"edge_functions",progress:{...progress,current:"Edge Functions"}});const t=tables[i],table=String(t.tablename||"");if(String(t.schemaname||"public")==="public"&&/^[A-Za-z_][A-Za-z0-9_]*$/.test(table))await destQuery(session.token,ref,`do $$ begin if not exists(select 1 from pg_catalog.pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=${qlit(table)}) then execute 'alter publication supabase_realtime add table public.${qid(table)}'; end if; end $$;`);return updateJob(sb,job,{progress:{...progress,realtime_index:i+1,current:`realtime ${table}`}})}
if(phase==="edge_functions"){const expected=Array.isArray(inventory.functionsExpected)?inventory.functionsExpected:[],deployed=Array.isArray(progress.functions_deployed)?progress.functions_deployed:[];if(expected.some((x:string)=>!deployed.includes(x)))return updateJob(sb,job,{status:"waiting",progress:{...progress,current:"Aguardando deploy das Edge Functions pelo GitHub App."}});return updateJob(sb,job,{status:"running",phase:"secrets",progress:{...progress,current:"Secrets"}},{level:"info",message:"Edge Functions concluídas."})}
if(phase==="secrets"){if(progress.secrets_expected&&!progress.secrets_handed_off)return updateJob(sb,job,{status:"waiting",progress:{...progress,current:"Aguardando handoff seguro dos Secrets."}});return updateJob(sb,job,{status:"running",phase:"config",progress:{...progress,current:"Configuração"}})}
if(phase==="config"){if(progress.config_expected&&!progress.config_applied)return updateJob(sb,job,{status:"waiting",progress:{...progress,current:"Aguardando configuração compatível."}});return updateJob(sb,job,{status:"running",phase:"verify",progress:{...progress,current:"Verificando destino"}})}
if(phase==="verify"){const rows:any=await destQuery(session.token,ref,"select bucket_id,count(*)::bigint as objects from storage.objects group by bucket_id order by bucket_id"),list=Array.isArray(rows)?rows:Array.isArray(rows?.result)?rows.result:[],targetObjects=list.reduce((n:number,x:any)=>n+Number(x.objects||0),0),expectedObjects=Number(inventory.totalObjects||0),warnings=Array.isArray(job.warnings)?[...job.warnings]:[];if(targetObjects<expectedObjects)warnings.push(`Storage verificado com ${targetObjects}/${expectedObjects} objeto(s).`);const done=await updateJob(sb,job,{status:"completed",phase:"done",progress:{...progress,current:"Concluído",target_objects:targetObjects},warnings,completed_at:new Date().toISOString()},{level:"info",message:"Assets e configurações concluídos."});await cleanup(sb,done);return done}
throw new Error(`ASSET_PHASE_INVALID:${phase}`)}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors});if(req.method!=="POST")return json({ok:false,code:"METHOD_NOT_ALLOWED"},405);const sb=admin();try{const body=await req.json().catch(()=>({})),action=String(body.action||"status");
if(action==="handoff"){const id=String(body.job_id||""),token=String(body.token||""),{data:job,error}=await sb.from("ld_cloud_asset_jobs").select("*").eq("id",id).maybeSingle();if(error||!job)throw new Error("ASSET_JOB_NOT_FOUND");if(await shaHex(token)!==String(job.handoff_token_hash||""))throw new Error("HANDOFF_FORBIDDEN");const db=String(body.db_url||""),url=String(body.supabase_url||""),key=String(body.source_key||"");if(!/^postgres(?:ql)?:\/\//i.test(db))throw new Error("SOURCE_DB_URL_INVALID");if(!/^https:\/\/[a-z0-9.-]+\.supabase\.co\/?$/i.test(url))throw new Error("SOURCE_SUPABASE_URL_INVALID");if(!key)throw new Error("SOURCE_SERVER_KEY_MISSING");await storeSecret(sb,String(job.source_db_secret_name),db,"Temporary Lovable Cloud DB URL for Build 7");await storeSecret(sb,String(job.source_url_secret_name),url.replace(/\/+$/,""),"Temporary Lovable Cloud API URL for Build 7");await storeSecret(sb,String(job.source_key_secret_name),key,"Temporary Lovable Cloud server key for Build 7");const updated=await updateJob(sb,job,{status:"helper_ready",phase:"inspect"},{level:"info",message:"Handoff server-to-server dos assets confirmado."});return json({ok:true,job:sanitize(updated)})}
if(action==="secrets_handoff"){const id=String(body.job_id||""),token=String(body.token||""),{data:job,error}=await sb.from("ld_cloud_asset_jobs").select("*").eq("id",id).maybeSingle();if(error||!job)throw new Error("ASSET_JOB_NOT_FOUND");if(await shaHex(token)!==String(job.handoff_token_hash||""))throw new Error("HANDOFF_FORBIDDEN");const values=body.secrets&&typeof body.secrets==="object"?body.secrets:{},secrets=Object.entries(values).filter(([name,value])=>/^[A-Z][A-Z0-9_]{1,127}$/.test(name)&&!BUILTIN_SECRETS.has(name)&&typeof value==="string"&&value.length>0).slice(0,100).map(([name,value])=>({name,value:String(value)}));if(secrets.length){const td=await accessToken(sb,String(job.license_id),String(job.device_hash));if(td.missing.length)return json({ok:false,code:"SUPABASE_REAUTH_REQUIRED",missing_scopes:td.missing},403);await management(td.token,`/projects/${encodeURIComponent(job.destination_project_ref)}/secrets`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(secrets)})}const updated=await updateJob(sb,job,{progress:{...(job.progress||{}),secrets_expected:Number(body.expected||secrets.length),secrets_handed_off:true,secrets_done:secrets.length}},{level:"info",message:`${secrets.length} Secret(s) compatível(is) aplicado(s).`});return json({ok:true,count:secrets.length,job:sanitize(updated)})}
const auth=await authorize(req,sb),td=await accessToken(sb,auth.licenseId,auth.deviceHash);if(td.missing.length)return json({ok:false,code:"SUPABASE_REAUTH_REQUIRED",missing_scopes:td.missing},403);
if(action==="prepare"){const projectId=String(body.lovable_project_id||""),dest=String(body.destination_project_ref||"");if(!projectId||!/^[a-z0-9]{8,32}$/i.test(dest))throw new Error("ASSET_PREPARE_INVALID");const projects=await management(td.token,"/projects");if(!Array.isArray(projects)||!projects.some((p:any)=>String(p.ref||p.id)===dest))throw new Error("DESTINATION_PROJECT_NOT_AUTHORIZED");const {data:active}=await sb.from("ld_cloud_asset_jobs").select("id,status").eq("license_id",auth.licenseId).eq("device_hash",auth.deviceHash).eq("lovable_project_id",projectId).in("status",["prepared","helper_ready","running","waiting"]).maybeSingle();if(active)return json({ok:false,code:"ASSET_JOB_ALREADY_ACTIVE",active_job:active},409);const id=crypto.randomUUID(),handoff=randomValue(48),n=names(id),row={id,license_id:auth.licenseId,device_hash:auth.deviceHash,lovable_project_id:projectId,lovable_project_name:String(body.lovable_project_name||""),source_project_ref:String(body.source_project_ref||""),destination_project_ref:dest,destination_project_name:String(body.destination_project_name||dest),handoff_token_hash:await shaHex(handoff),source_db_secret_name:n.db,source_url_secret_name:n.url,source_key_secret_name:n.api,status:"prepared",phase:"prepare",progress:{},inventory:{},warnings:[],logs:[{at:new Date().toISOString(),level:"info",message:"Job complementar Build 7 preparado."}]};const {data,error}=await sb.from("ld_cloud_asset_jobs").insert(row).select("*").single();if(error)throw new Error("ASSET_JOB_CREATE_FAILED");return json({ok:true,job:sanitize(data),handoff_token:handoff,broker_handoff_url:`${Deno.env.get("SUPABASE_URL")}/functions/v1/ld-cloud-migrator-assets`})}
if(action==="active"){const projectId=String(body.lovable_project_id||""),{data}=await sb.from("ld_cloud_asset_jobs").select("*").eq("license_id",auth.licenseId).eq("device_hash",auth.deviceHash).eq("lovable_project_id",projectId).in("status",["prepared","helper_ready","running","waiting"]).order("created_at",{ascending:false}).limit(1).maybeSingle();return json({ok:true,job:sanitize(data)})}
const job=await ownedJob(sb,String(body.job_id||""),auth);if(action==="status")return json({ok:true,job:sanitize(job)});
if(action==="inspect"){if(!["helper_ready","running","waiting"].includes(job.status))throw new Error("ASSET_JOB_NOT_READY");const inventory=await inspect(sb,job),updated=await updateJob(sb,job,{status:"running",phase:"storage_buckets",inventory:{...job.inventory,...inventory},progress:{...(job.progress||{}),bucket_index:0,objects_done:0,object_offset:0}},{level:"info",message:`Storage: ${inventory.buckets.length} bucket(s), ${inventory.totalObjects} objeto(s).`});return json({ok:true,job:sanitize(updated)})}
if(action==="functions_manifest"){const functions=Array.isArray(body.functions)?[...new Set(body.functions.map((x:any)=>String(x)).filter((x:string)=>/^[a-z0-9][a-z0-9_-]{0,63}$/i.test(x)))].sort():[],updated=await updateJob(sb,job,{inventory:{...(job.inventory||{}),functionsExpected:functions},progress:{...(job.progress||{}),functions_deployed:Array.isArray(job.progress?.functions_deployed)?job.progress.functions_deployed:[]}},{level:"info",message:`${functions.length} Edge Function(s) detectada(s) no GitHub.`});return json({ok:true,job:sanitize(updated)})}
if(action==="deploy_function"){const slug=String(body.slug||"");await deployFunction(td.token,String(job.destination_project_ref),slug,body.files,body.verify_jwt!==false);const deployed=[...new Set([...(Array.isArray(job.progress?.functions_deployed)?job.progress.functions_deployed:[]),slug])],updated=await updateJob(sb,job,{progress:{...(job.progress||{}),functions_deployed:deployed,current:`function ${slug}`}},{level:"info",message:`Edge Function ${slug} implantada.`});return json({ok:true,job:sanitize(updated)})}
if(action==="apply_config"){const cfg=safeConfig(body.config||{});if(Object.keys(cfg.auth).length)await management(td.token,`/projects/${encodeURIComponent(job.destination_project_ref)}/config/auth`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(cfg.auth)});const warnings=[...(Array.isArray(job.warnings)?job.warnings:[]),...(Array.isArray(body.warnings)?body.warnings.map((x:any)=>String(x).slice(0,500)):[])],updated=await updateJob(sb,job,{progress:{...(job.progress||{}),config_expected:true,config_applied:true},warnings},{level:"info",message:"Configuração Auth portátil aplicada."});return json({ok:true,job:sanitize(updated)})}
if(action==="run_next"){try{return json({ok:true,job:sanitize(await runNext(sb,job,auth))})}catch(error:any){if(error?.missingScopes)return json({ok:false,code:"SUPABASE_REAUTH_REQUIRED",missing_scopes:error.missingScopes},403);const failed=await updateJob(sb,job,{status:"failed",last_error:String(error?.message||error).slice(0,900)},{level:"error",message:String(error?.message||error)});await cleanup(sb,failed);return json({ok:false,code:"ASSET_UNIT_FAILED",job:sanitize(failed)},500)}}
if(action==="cancel"){const cancelled=await updateJob(sb,job,{status:"cancelled",cancelled_at:new Date().toISOString()},{level:"warn",message:"Migração complementar cancelada."});await cleanup(sb,cancelled);return json({ok:true,job:sanitize(cancelled)})}
throw new Error("UNKNOWN_ACTION")}catch(error:any){const message=String(error?.message||error),status=/FORBIDDEN|NOT_AUTHORIZED|REAUTH/.test(message)?403:400;return json({ok:false,code:message},status)}});
